### ISSUE TITLE
Leaderboard not working?

### ISSUE THREAD

**Issue by NeatMonster** [pulviscriptor/agario-client#100]
For some strange reason, Agar.io's servers now return 0 instead of the blob ID of each of the leaders.
Tested using the latest version of `agario-client` and `NodeJS` v0.12.7, you can clearly see in the dump that all `uint32` blob IDs have the value 0 whereas all `end_str16` nicknames are okay.

    worker: RECV packet ID=49 LEN=179
    worker: dump: 31 0a 00 00 00 00 00 00 00 5a 00 45 00 52 00 4f 00 00 00 00 00 00 00 00 00 00 00 00 00 49 00 27 00 6d 00 4e 00 6f 00 6f 00 62 00 42 00 75 00 74 00 54 00 6f 00 70 00 31 00 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 16 30 e9 15 e4 01 17 30 e9 15 72 00 63 00 61 00 64 00 65 00 e4 01 6f 00 00 00 00 00 00 00 48 00 6f 00 64 00 6f 00 72 00 00 00 00 00 00 00 62 00 75 00 6c 00 67 00 61 00 72 00 69 00 61 00 00 00 00 00 00 00 16 30 e9 15 e4 01 17 30 41 00 72 00 63 00 61 00 64 00 65 00 47 00 6f 00 d0 63 00 00 00 00 00 00 00 00
    worker: leaders update: [0,0,0,0,0,0,0,0,0,0]
    worker: leaders on server: 〖ᗩǤ〗ArcadeGo提, 〖ᗩǤ〗ArcadeGo提, 〖ᗩǤ〗ArcadeGo提, 〖ᗩǤ〗ArcadeGo提, 〖ᗩǤ〗ArcadeGo提, 〖ᗩǤ〗ArcadeGo提, 〖ᗩǤ〗ArcadeGo提, 〖ᗩǤ〗ArcadeGo提, 〖ᗩǤ〗ArcadeGo提, 〖ᗩǤ〗ArcadeGo提

([Full log on Pastebin](http://pastebin.com/VA3wamp2))

**Comment by pulviscriptor** [comment]
It is broken by agar. 
I can't do fix right now, if somebody could do PR that would be nice.

**Comment by NeatMonster** [comment]
Thing is, how do we recover the blob ID? I might be wrong, but we can't use the name to look it up because it is not unique for each server.

**Comment by michaelcurry** [comment]
looks like they have removed the ball_id form ID 49 all together.

**Comment by xzfc** [comment]
Server returns 1 for the player's leaderboard item.

**Comment by pulviscriptor** [comment]
Event fixed in https://github.com/pulviscriptor/agario-client/pull/120
