### ISSUE TITLE
properly destroy agario-client instance

### ISSUE THREAD

**Issue by henopied** [pulviscriptor/agario-client#103]
I have multiple connections to a server but when one disconnects I try to connect it a few times but if it fails I attempt to destroy everything about that connection but then sometimes it is still able to connect after that but then it doesn't have a client or anything so it throws an error.

**Comment by q3wzeck** [comment]
`end();` ?

**Comment by issy123** [comment]
I have contacted u personally, and as far as i could see this is an user-defined code problem.
Has nothing to do with `agario-client`

**Comment by pulviscriptor** [comment]
@henopied 
>so it throws an error

Please show this error.
