### ISSUE TITLE
window.agar in packet.js ??

### ISSUE THREAD

**Issue by agarioBotDev** [pulviscriptor/agario-client#104]
hi pulviscriptor,

in the browser you get a lot of values from the object window.agar for examples window.agar.Cells - there is also the window.agar.dimensions value(s). It gives you a few "numbers" i need. For my ambitions i need the window.agar.dimensions values my bots "have". Any idea in which of theese packets this can "hide". I hope you even understood my question.

greets,
david

**Comment by pulviscriptor** [comment]
Uhm, there is no `window.agar` on http://agar.io. Maybe you installed some extension that created it for you.
So i don't know what you have in `window.agar.dimensions`. But this is some extension, you can check its source code and find out yourself.

**Comment by Sonicmaster13** [comment]
@pulviscriptor The extension he is using it called Agar Expose, it is a modding utility. Your client, however, does have what he means. @agarioBotDev I think you should be able to add an array called botDimensions and every time you get set packet 64, border update, you could do botDimensions.push with all the dimensions.

**Comment by DaAwesomeRazor** [comment]
@agarioBotDev You would use onMapSizeLoad to do that

**Comment by agarioBotDev** [comment]
I "found" the dimensions in packet.js, but it's not what i thought it is. ;(
