### ISSUE TITLE
Detect bot death

### ISSUE THREAD

**Issue by Sonicmaster13** [pulviscriptor/agario-client#105]
How, in my own client, would i detect for a bot death? I haven't seen anything be sent on a player death, so i have no idea....

**Comment by q3wzeck** [comment]
`on.lostMyBalls()`

**Comment by Sonicmaster13** [comment]
lemme say again: '... in my own client...'

**Comment by issy123** [comment]
Packet id 16 contains the removal data/event as readed here:
http://agar.gcommer.com/index.php?title=Protocol#World_Update_.28opcode_16.29
