### ISSUE TITLE
error: cannot read property client of null

### ISSUE THREAD

**Issue by agarioBotDev** [pulviscriptor/agario-client#107]
i have an array where my agario-clients are 'stored'.

```javascript
var clients = new Array(4);
for ( var i = 0; i < clients.length; i++) {
       clients[i] = new Array(1000); // the array is multidimensional but don't think it affects it, in clients[1] the client objects are stored
}
```
and then when i try:

```javascript
for (var i = 0; i < clients[0].length; i++) {
     clients[1][i].client.split();
}
```

a few split and then it crashes and i get the error: cannot read property client of null...any ideas how to fix ?

I thought maybe sometimes somehow the "client" goes "flying" xD - because it still collects food i tried:
```javascript
bot.client.on('myNewBall', function (ball_id) {
            // Should always be generated.
           clients[1][bot.bot_id] = this; // to reset the obejct - it puts itself to his old position in the array
                    
});
```

but didn't work....

**Comment by issy123** [comment]
There is no property "lenght" but there is "length"

I recommand using an IDE like eclipse,webstorm,netbeans and more that are intelligent enough to detect those errrors for you

**Comment by agarioBotDev** [comment]
@issy123 my fault i wrote it wrong, but it's not why i get this error...any idea how to fix ?

**Comment by agarioBotDev** [comment]
@issy123 got the error fixed.
