### ISSUE TITLE
How to use multiple accounts?

### ISSUE THREAD

**Issue by Lukkez** [pulviscriptor/agario-client#108]
Someone can send? I don't know much about this "agario-client" and i want fb bots, if someone can thx.

**Comment by DaAwesomeRazor** [comment]
var facebookTokens = ["tokengoeshere", "token2goeshere"]

this.client.authToken = facebookTokens[this.bot_id]

**Comment by Lukkez** [comment]
Thanks :D

**Comment by Lukkez** [comment]
But this work on ogar-feeder-bot?

**Comment by Lukkez** [comment]
I don't need the datr, xs and c_user cookies?

**Comment by Lukkez** [comment]
```
var auth_token = null;
 
 if (config.useFacebookAuth) {
     var account = new AgarioClient.Account();

     account.c_user = config.account.c_user;
     account.datr = config.account.datr;
     account.xs = config.account.xs;
 
     account.requestFBToken(function(token, info) {
         auth_token = token;
     });
 
 }
 
 if (config.account.token != "") {
     auth_token = config.account.token;
 }
  ``` 
This works for multiple accounts too?

**Comment by agarioBotDev** [comment]
@Lukkez has nothing to do with agario-client, ask in ogar-feeder-bot issue.

**Comment by Lukkez** [comment]
ogar-feeder-bot uses agario-client -_-

**Comment by DaAwesomeRazor** [comment]
Well I said how to do it with agario-client, Im too lazy to look how ogar feederbot does it.
