### ISSUE TITLE
Multiple clients think they share balls.

### ISSUE THREAD

**Issue by JavaGT** [pulviscriptor/agario-client#11]
If I create more than one client ('main' and "extra") then spawn them both into the game (I am putting them into the same game via a http request loop) calling main.my_balls returns ['xxxx','yyyy'] while calling extra.my_balls also returns ['xxxx','yyyy'], I believe one should be returning ['xxxx'] and the other ['yyyy'].

Sorry if there is a method implemented to get around this that I have missed.

**Comment by pulviscriptor** [comment]
Oops.

**Comment by pulviscriptor** [comment]
Now it should work.

**Comment by RouxRC** [comment]
Nice catch! This probably solves a similar problem I had and could not figure out. Thanks!
