### ISSUE TITLE
agario-client help error

### ISSUE THREAD

**Issue by Juampab12** [pulviscriptor/agario-client#110]
C:\Users\JuanPablo\Desktop\ogar-feeder-bot-master\node_modules\agario-client\aga
rio-client.js:172
            throw err;
            ^

TypeError: client.emittEvent is not a function
    at Client.processors.64 (C:\Users\JuanPablo\Desktop\ogar-feeder-bot-master\n
ode_modules\agario-client\agario-client.js:440:20)
    at Object.Client.onMessage (C:\Users\JuanPablo\Desktop\ogar-feeder-bot-maste
r\node_modules\agario-client\agario-client.js:154:13)
    at WebSocket.onMessage (C:\Users\JuanPablo\Desktop\ogar-feeder-bot-master\no
de_modules\ws\lib\WebSocket.js:418:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (C:\Users\JuanPablo\Desktop\ogar-feeder-bot-master\node
_modules\ws\lib\WebSocket.js:823:10)
    at C:\Users\JuanPablo\Desktop\ogar-feeder-bot-master\node_modules\ws\lib\Rec
eiver.js:537:18
    at Receiver.applyExtensions (C:\Users\JuanPablo\Desktop\ogar-feeder-bot-mast
er\node_modules\ws\lib\Receiver.js:364:5)
    at C:\Users\JuanPablo\Desktop\ogar-feeder-bot-master\node_modules\ws\lib\Rec
eiver.js:531:14
    at Receiver.flush (C:\Users\JuanPablo\Desktop\ogar-feeder-bot-master\node_mo
dules\ws\lib\Receiver.js:340:3)

C:\Users\JuanPablo\Desktop\ogar-feeder-bot-master>pause
Press any key to continue . . .

PLEASE HELP NOTHING WORKS

Here´s the error:
 onPacketError: function(packet, err) {
        var crash = true;

        this.emitEvent('packetError', packet, err, function() {
            crash = false;
        });

        if(crash) {
            if(this.debug >= 1)
                this.log('Packet error detected! Check packetError event in README.md');
            throw err; // <- LINE 72
        }
    },

**Comment by pulviscriptor** [comment]
>TypeError: client.emittEvent is not a function

There is no `emittEvent` word in https://github.com/pulviscriptor/agario-client/blob/master/agario-client.js
If you modified your `agario-client.js` manually then replace it to `emitEvent`. 
Otherwise i'm not sure what is happening. There shouldn't be `emittEvent` word.

**Comment by Juampab12** [comment]
OMG Im such a retard sorry for making u waste time
