### ISSUE TITLE
Unknown Packed id "104"

### ISSUE THREAD

**Issue by hassanila97** [pulviscriptor/agario-client#111]
What is this packed.. . it's pretty new

![namnlos](https://cloud.githubusercontent.com/assets/15068696/13846963/e95ca92e-ec4a-11e5-98cc-b013e77bb031.png)

**Comment by Juampab12** [comment]
You mean packet "68"?

**Comment by hassanila97** [comment]
Yes exactly, thx :)

**Comment by pulviscriptor** [comment]
Its ID=104 and its dump is 1 byte 0x64 which is 104
Original code does this:
```javascript
        case 104:
          c.logout();
```
So i think i just will add another event like `client.on.logoutRequest`.

**Comment by hassanila97** [comment]
Yes do it thx...  I need it to know when its logging out and be able to properly logout...   THX
