### ISSUE TITLE
facebook bots create?

### ISSUE THREAD

**Issue by nicolaspielt** [pulviscriptor/agario-client#113]
can any one tell me how I create Facebook bots?

**Comment by MasonBurdette** [comment]
client.auth_token (1 FB per Account per server)

**Comment by nicolaspielt** [comment]
@MasonBurdette and where is it?

**Comment by MasonBurdette** [comment]
@nicolaspielt you have to define it :P, look at example folder.

**Comment by nicolaspielt** [comment]
@MasonBurdette and can you tell me to say what to write in there client.auth_token = '';

**Comment by MasonBurdette** [comment]
the token (generate it)

**Comment by nicolaspielt** [comment]
@MasonBurdette you can write me an example xD

**Comment by nicolaspielt** [comment]
@MasonBurdette can sent me a script?

**Comment by pulviscriptor** [comment]
@nicolaspielt
Doc https://github.com/pulviscriptor/agario-client/blob/master/README.md#auth-token
Example https://github.com/pulviscriptor/agario-client/blob/master/examples/auth_token.js

**Comment by nicolaspielt** [comment]
@MasonBurdette @pulviscriptor  Ok I'm really too stupid :D can one again to tell me how to correctly Facebook bots created or send a code pls.

**Comment by nicolaspielt** [comment]
@MasonBurdette Skype Name?
