### ISSUE TITLE
srv.key???

### ISSUE THREAD

**Issue by AmazingGamerBoy** [pulviscriptor/agario-client#117]
Why is this srv.key needed? why cant u just connect to the agar server with just an ip:port and websocket? what does the key do?

**Comment by pulviscriptor** [comment]
Client sends it to server in packet ID 80 https://github.com/pulviscriptor/agario-client/blob/master/agario-client.js#L100

**Comment by AmazingGamerBoy** [comment]
So if I connect to an Agario server, and I get my bots to connect to that exact same server, will their keys be the same as everyone else's that are connected to the same server? Or are they different?

**Comment by pulviscriptor** [comment]
On party servers key will be same for everybody, which is party ID.
On FFA servers they are generated randomly when you request FFA server, like:
```
aXpjR0txQFZMa3t3aGhlZH1vf1lyYH5vbWFjXkdvVltUdW5uY3lhYHx3el56f3pla3pqSQ==
a3h8WEt2QF5CdmBxZmhqZXx9dkl6fnZ5aXdnR0J2WkFMcW5zcnRhdHh7e1F/eX5mbn9qXkth
aXpjR0txQFZMa3twaGhlZHpvf1lyYH5vbWFjXkdvVltUdW5uY3lhYHx3el56f3hnaHdmSQ==
```

**Comment by AmazingGamerBoy** [comment]
If I have bots connected to an IP I already know, do they all have to request a key individually?

**Comment by pulviscriptor** [comment]
@AmazingGamerBoy
Only for FFA. For party you can use same IP and key multiple times.

**Comment by AmazingGamerBoy** [comment]
Thanks pulv!

**Comment by AmazingGamerBoy** [comment]
Very, very last question, soz for them all, but if I know the IP of a server, how would I request a key from it? I only know how to do it if u are requesting ip and key, but this one is just the key. Thanks!

**Comment by pulviscriptor** [comment]
@AmazingGamerBoy
