### ISSUE TITLE
connection error:  socket closed

### ISSUE THREAD

**Issue by d-bots-client** [pulviscriptor/agario-client#118]
Hello,

since the update i'm always getting the error: connection error: socket closed.
I think the server closes the socket..i don't need an solution i only want to knnow what happened.
Did the agar.io server rejected the client ? (i changed my init key)
The proxies i use aren't bad ones, and before the update they worked perfect. My other thougt was that  agar.io banned my ip's.... do you know what happened ?

Thanks,
David

**Comment by pulviscriptor** [comment]
Do you use agario-client version `1.3.0`?
`examples/basic.js` works fine for me, is it broken for you?

**Comment by d-bots-client** [comment]
yes I do....
