### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by henopied** [pulviscriptor/agario-client#12]
I am currently trying to make the ogar bot work with your client but I am wondering is ball.size the size (radius) or mass and if it is size would Math.Pow(ball.size,2)/100 work to get mass?

**Comment by RouxRC** [comment]
Personally I do `parseInt(Math.pow(ball.size/10, 2))` which is indeed the same :)

**Comment by henopied** [comment]
Speedy response! And thanks for the answer. I am very exited about the ogar bot.

**Comment by pulviscriptor** [comment]
henopied, until it will be implemented* you can use little hack:
```
client.on('ballResize', function(ball_id, old_size, new_size) {
	client.balls[ball_id].mass = parseInt(Math.pow(new_size/10, 2));
});
```
Didn't tested it* but you got the idea.
<sub><sup>*In 16 hours my both HDDs died with all development/testing environment, so i don't know when i will be able to do this</sup></sub>

**Comment by henopied** [comment]
Thanks very much

**Comment by henopied** [comment]
Also will this run when the balls are loaded or later?

**Comment by pulviscriptor** [comment]
henopied, this will run when we update size of ball. Initially ball have size 0 and mass will be undefined (for example we know only ball ID from top 10 players).
When ball will appear in our field of view then size will updated and mass will be created.

**Comment by pulviscriptor** [comment]
henopied, added `ball.mass`, you can remove your patch from your code.

**Comment by henopied** [comment]
I actually gave up on that for now I am working on making it work with apos launcher and adding some enhancements such as wall code currently I have a getmass function but I defiantly want to port it over maybe I will create my own bot from scratch :)

**Comment by henopied** [comment]
Also is [parseint](https://github.com/pulviscriptor/agario-client/blob/master/agario-client.js#L524) really necessary?
