### ISSUE TITLE
Connecting to different server with same ws... ??

### ISSUE THREAD

**Issue by agarioBotDev** [pulviscriptor/agario-client#123]
Hello,

when I try to connect 100 clients to the same server, there're about 4 different leaderboard's i get.
I KNOW that the leaderboard is broken in agario-client, but before the last update I got the same 'broken' leaderboard for each client. Only about 20 clients connect to the "right" server, the other's connect somehow to a different one, look on the picture.

![agar](https://cloud.githubusercontent.com/assets/16101422/13903813/09728dfa-ee8a-11e5-956b-144e52489c4f.png)

**Comment by pulviscriptor** [comment]
Before 1.3.1 there was broken `leaderBoardUpdate` event and basically it was returning 10 nicknames of last top player. Upgrade your client to 1.3.1 or patch yours https://github.com/pulviscriptor/agario-client/commit/73d4ec517e3213529196ff4beb5fe8e543b02086 to see real nicknames.
Maybe everything is working but last player in leader board is changes between your connections.
