### ISSUE TITLE
coordinate problems...

### ISSUE THREAD

**Issue by agarioBotDev** [pulviscriptor/agario-client#124]
Hello,

I just opened basic.js, , modified a bit (just showing map size and ball coordinates) and run it...I noticied that somehow the y coordinate of my_ball is smaller then the min_y of the map ? How is this possible ??

![agar](https://cloud.githubusercontent.com/assets/16101422/13956006/316ab3aa-f047-11e5-8fda-4b535b7ff66d.png)

**Comment by pulviscriptor** [comment]
As i see on screenshot, map Y size is from 1653 to 3842 and you in 3273 which is in the middle.

**Comment by agarioBotDev** [comment]
@pulviscriptor oh i'm such a dump ass, i thougt my_ball.x is -3273 and min_y is -1653...props to me, making the ' - ' in conole.log :c. ;)
