### ISSUE TITLE
X & Y coordinates in spectator mode

### ISSUE THREAD

**Issue by GustavGenberg** [pulviscriptor/agario-client#127]
I'm not quite sure about this, and thats why I'm asking. If you put a bot in spectator mode and enable the "camera" spectate mode, can you get the X and Y coordinates from it then? I've read that you're getting the X and Y coordinates from client.ball.x & client.ball.y. When the bot is spectating, does it have a like "ball" (client._ball_.x etc) ?

This is not a real issue, but I really need to know... I'm happy to hear from you!

**Comment by pulviscriptor** [comment]
`client.on.spectateFieldUpdate(cord_x, cord_y, zoom_level)`

**Comment by GustavGenberg** [comment]
Oh....

Didnt see that... sorry... 
It was so simple...
Thank you!
