### ISSUE TITLE
Facebook Bots patched!!

### ISSUE THREAD

**Issue by philw1508** [pulviscriptor/agario-client#129]
everything works normal but with no facebook mass... so its like 10 mass bots... but its strange that all my tokens work.... maybe we have to get some other sort than datr c_user or xs cookies

**Comment by xXx-stalin-666-money-xXx** [comment]
I am a developer of my own agario client in C and I think that they have disabled opcode 82 that was used to login, now official client sends the FB token in a packet with opcode 0x66 (102), however the format of this packet is unknown (to me)

**Comment by agarioBotDev** [comment]
@xXx-stalin-666-money-xXx that would be a bit strange, normally the client never send an 102....and even i didn't change anything to my extension and the fb login still works, seems to be something different

**Comment by agarioBotDev** [comment]
@xXx-stalin-666-money-xXx i'm. skype: david_the_biggest_

**Comment by agarioBotDev** [comment]
@xXx-stalin-666-money-xXx actually not unlimited fb bots, i hae that already, but 132 mass bots - and programming that in C# sounds interesting too

**Comment by thisismo** [comment]
Do you get better performance with your rewritten Client?

**Comment by skillize** [comment]
if(this.auth_token) {
            buf = new Buffer(2 + this.auth_token.length);
            buf.writeUInt8(102, 0);
            buf.writeUInt8(this.auth_provider, 1);
            for (i=1;i<=this.auth_token.length;++i) {
                buf.writeUInt8(this.auth_token.charCodeAt(i-1), i+1);

i changed this still not working, how 2 fix?

**Comment by xXx-stalin-666-money-xXx** [comment]
@skillize 

This is the packet format in HEX..

66 08 01 12 [token_len+25] 01 08 0a 52 [token_len+20] 01 0a 0d 08 05 12 05 31 2e 34 2e 39 18 00 20 00 10 02 1a [token_len] 01 [token_itself]

And if it still doesn't work, you have probably been banned - check https://www.reddit.com/r/Agario/comments/4cl4vq/i_keep_getting_instantly_kicked/

**Comment by ElieeCh** [comment]
I still can't seem to fix it, eventhough I tried everything.. Can you help me @xXx-stalin-666-money-xXx
