### ISSUE TITLE
Client don't respawn ball

### ISSUE THREAD

**Issue by KristophPOL** [pulviscriptor/agario-client#13]
Sry, but i have problem with client, if someone eat me my ball don't respawn. I don't know why ;/ can you help me ? 

worker: closest 3537658, distance 85.70880934886448
worker: closest 3537658, distance 54.45181356024793
worker: I ate 3537658, my new size is 44
worker: closest 3539285, distance 549.626236637226
worker: closest 3539285, distance 532.2593352868506
worker: closest 3539285, distance 486.64257931257924
3529797(Alan PL) ate my ball
i lost my ball 3539702, 0 balls left
worker: lost all my balls, respawning

And nothing more .... just stay

**Comment by pulviscriptor** [comment]
KristophPOL,
I can't reproduce this issue. 
If it is still there, can you please edit `example.js`, set `client.debug = 5;`, do `node example.js > debug.log`, upload `debug.log` to somewhere like [pastebin.com](http://pastebin.com) and provide link to it.

**Comment by KristophPOL** [comment]
pulviscriptor, 
I repair this , i can't programist but works ;p hehe 
In client-agario.js (//leaderboard update in FFA mode) i add 
client.emit('lostMyBalls');


client.on('lostMyBalls', function() 
{ 
	var my_ball = client.balls[ client.my_balls[0] ];
	if(my_ball) return;
    client.log('lost all my balls, respawning');
    client.spawn('Poland'); //spawning new ball with nickname "agario-client"
});


Stupid but works

**Comment by KristophPOL** [comment]
i don't know why but client always check leaderboard when i die

**Comment by pulviscriptor** [comment]
KristophPOL,
Uhm... Can you please run [example.js](https://raw.githubusercontent.com/pulviscriptor/agario-client/master/example.js) is it have same issue?
If yes, then can you please provide debug.log?

**Comment by KristophPOL** [comment]
i always play example.js 
Where is this file ?

**Comment by pulviscriptor** [comment]
KristophPOL,
- create new folder
- go in it
- do `npm install agario-client`
- do `node ./node_modules/agario-client/example.js`

Is it working fine?

**Comment by KristophPOL** [comment]
Sometimes not respawn new ball , if i change this 

client.on('lostMyBalls', function() 
{ 
var my_ball = client.balls[ client.my_balls[0] ];
if(my_ball) return;
client.log('lost all my balls, respawning');
client.spawn('Poland'); //spawning new ball with nickname "agario-client"
});

Works...

**Comment by pulviscriptor** [comment]
KristophPOL,
Let's try this:
- create new folder
- go there
- do `git clone https://github.com/pulviscriptor/agario-client -b unstable_spawn_fix`
- do `cd agario-client/`
- do `npm install`
- do `node example.js`

Is it working stable now?
*I still can't reproduce issue, but there was some spawn() stability issues in past, so i hope this will fix them.

**Comment by pulviscriptor** [comment]
KristophPOL, update your client and check if problem is still there.

**Comment by KristophPOL** [comment]
its working now :) good job :) can you tell me how connect more then 5 bots ? Agar.io block connect if you have 4 or 5 client on the same server, maybe proxy ?  sry for my english

**Comment by KristophPOL** [comment]
ball.is_friend = true; //set ball.is_friend to true
                   ^
TypeError: Cannot set property 'is_friend' of undefined
    at Object.AgarioClient.addFriend (/root/node_modules/agario-client/example.js:25:20)

**Comment by pulviscriptor** [comment]
KristophPOL,
>can you tell me how connect more then 5 bots ?

agario-client do not have support of proxy/socks servers. 
You may google for tricks to make application work through SOCKS4/SOCKS5 server or something like that.
If you have your own servers, you can use [vanessa_socket_pipe](http://linux.die.net/man/1/vanessa_socket_pipe)
>TypeError: Cannot set property 'is_friend' of undefined

Is this original non edited `example.js`? 
I don't think it is because of `example.js:25:20` is wrong for [that code](https://github.com/pulviscriptor/agario-client/blob/master/example.js#L17).
And `addFriend()` called by [client.on.ballAppear](https://github.com/pulviscriptor/agario-client/blob/master/example.js#L33) so `ball` is not `undefined`
Can you show your `example.js`?

**Comment by KristophPOL** [comment]
I add to my script loop , i send you later if come back to home

**Comment by KristophPOL** [comment]
Can you help me how connect to agario party via vanessa_socket_pipe ? i can pay you for this ...

**Comment by pulviscriptor** [comment]
KristophPOL,
This is not agario-client related issue anymore so if you need more non-related help, try find help somewhere else or [email me](mailto:pulviscriptor@gmail.com).
And vanessa_socket_pipe is easy to use. For example you connect to party http://agar.io/#B4XFC so you do:

    AgarioClient.servers.getPartyServer({party_key: 'B4XFC'}, function(srv) { ...

You see:

    Connecting to 37.187.163.132:1502 with key B4XFC

Then you connect to your server, for example your server have IP 1.2.3.4

    ssh root@1.2.3.4

Then you do on the server:

    vanessa_socket_pipe -L 44444 -o 37.187.163.132 -O 1502

Then you do in your.js

    client.connect('ws://1.2.3.4:44444', 'B4XFC');

Congratulations! You connected to party server from IP 1.2.3.4 using agario-client on your home PC.

![Image](https://i.imgur.com/DvWDAaG.png)

**Comment by KristophPOL** [comment]
ok thx :) i write you email , btw your script work good. i have wrong code in my script and got this error "TypeError: Cannot set property 'is_friend' of undefined", now works all.

**Comment by AmazingGamerBoy** [comment]
Anyone willing to help me create an agario suicide/feeder bot with over 150 bots? This needs to be a local script. It would be fine to edit another script such as pulviscriptor's. Will pay a bit of money if you want (but just a bit). Add me on skype to talk about this: Agario-Lord
My GitHub Account: AmazingGamerBoy
