### ISSUE TITLE
TypeError: value is out of bounds

### ISSUE THREAD

**Issue by thisismo** [pulviscriptor/agario-client#132]
TypeError: value is out of bounds
server-1     at checkInt (buffer.js:873:11)
server-1     at Buffer.writeUInt8 (buffer.js:921:5)
server-1     at Object.Client.onConnect (/root/server/node_modules/agario-client/agario-client.js:117:15)
server-1     at WebSocket.onOpen (/root/server/node_modules/ws/lib/WebSocket.js:432:14)
server-1     at emitNone (events.js:80:13)
server-1     at WebSocket.emit (events.js:179:7)
server-1     at WebSocket.establishConnection (/root/server/node_modules/ws/lib/WebSocket.js:862:8)
server-1     at ClientRequest.upgrade (/root/server/node_modules/ws/lib/WebSocket.js:753:25)
server-1     at ClientRequest.g (events.js:273:16)
server-1     at emitThree (events.js:110:13)
server-1     at ClientRequest.emit (events.js:188:7)

**Comment by SzAmmi** [comment]
When did u get this error? What did u do? Please explain more.

**Comment by SrNicolas** [comment]
Error is emited whan you run ogar-feeder-bot no modifications :P

**Comment by thisismo** [comment]
no i'm not using ogar-feeder-bot.

**Comment by SrNicolas** [comment]
Its just an example of what code can emit this error

**Comment by pulviscriptor** [comment]
@thisismo 
>server-1 at Object.Client.onConnect (/root/server/node_modules/agario-client/agario-client.js:117:15)

Can you show your `/root/server/node_modules/agario-client/agario-client.js`?
I'm not sure what is problem in line 117 there https://github.com/pulviscriptor/agario-client/blob/master/agario-client.js#L117

**Comment by pulviscriptor** [comment]
No action for a month, closing issue.
If you have same crash in same line and found this page in search, probably reason of crash is invalid token
https://github.com/pulviscriptor/agario-client/issues/154#issuecomment-210862498
