### ISSUE TITLE
Packet 18 (opcode) is missing.

### ISSUE THREAD

**Issue by SzAmmi** [pulviscriptor/agario-client#133]
```
worker: [warning] unknown packet ID(18): 12
```
In original code (http://agar.io/main_out.js) it resets all cells. It's defined here too: http://agar.gcommer.com/index.php?title=Protocol#Reset_all_cells_.28opcode_18.29

Can you fix it please?

**Comment by agarioBotDev** [comment]
@SzAmmi already fixed, update your agaio-client:
```javascript
'18': function() {
            for(var k in this.balls) if(this.balls.hasOwnProperty(k)) this.balls[k].destroy({'reason':'server-forced'});
        },
```

**Comment by SzAmmi** [comment]
Thanks.
