### ISSUE TITLE
Not Connecting, but no error... ??

### ISSUE THREAD

**Issue by agarioBotDev** [pulviscriptor/agario-client#134]
hi pulviscriptor,

i have a weird problem....it seems to work normal, but after 'Connecting to (server)' it just do nothing...no error...rly weird - picture of it (waited half an hour):
![agar](https://cloud.githubusercontent.com/assets/16101422/14188083/8929c2a2-f786-11e5-8f6f-029f7c5cad2c.png)

any ideas to help/fix ? :)

**Comment by pulviscriptor** [comment]
Is it repeating? 
Is it working in `basic.js`?
Do you use proxy/socks? 
Can you inspect connections using [wireshark](https://www.wireshark.org/download.html) / [Microsoft Network Monitor](https://www.microsoft.com/en-us/download/details.aspx?id=4865) to check if there connections made?

**Comment by agarioBotDev** [comment]
@pulviscriptor i do not see any packets from the server (151.80.96.58:1510) or to the server....but a lot of packets from and to a similiar server ip (annother agar.ioserver ? maybe from the browser ?):
![agar](https://cloud.githubusercontent.com/assets/16101422/14204317/c0ea1282-f803-11e5-9c8f-fa5921b81abd.png)

**Comment by agarioBotDev** [comment]
@pulviscriptor edit: the problems is since i changed my server-client communication to class ws (from socket.io)...

**Comment by agarioBotDev** [comment]
@pulviscriptor i think i did it wrong - i get packets from and to the server, but seems to be browser..how can i check if a connection is made ? I use proxies, but high quality ones...even when the proxies would be the problem, i would get an ECONNREFUSED (proxy ip), but not nothing

**Comment by pulviscriptor** [comment]
>but seems to be browser..how can i check if a connection is made

Close browser before test?
Since nobody else reported same problem for last 16 hours there is high chance that problem is in your code. 
Set `client.debug=5;` and see what is happens there.

**Comment by agarioBotDev** [comment]
@pulviscriptor it happens nothing...to set the key didn't help:
![agar](https://cloud.githubusercontent.com/assets/16101422/14206783/cc49caac-f815-11e5-96ae-7901d2b2ff2c.png)

**Comment by pulviscriptor** [comment]
There is listener for `ws.onopen` event https://github.com/pulviscriptor/agario-client/blob/master/agario-client.js#L46 which is output message about it https://github.com/pulviscriptor/agario-client/blob/master/agario-client.js#L80
So as i see `ws.onopen` is never called for some reason.
You need to see it using network analyzer, is there SYN/ACK packet from server or not. 
And did you modified `ws` library?
Also if you use some `client.agent` it can be reason too.

**Comment by agarioBotDev** [comment]
@pulviscriptor you are right, it is because of the agent, without it works^^....but the agent worked the hole time you have an idea why it doesn't work anymore ??

**Comment by agarioBotDev** [comment]
@pulviscriptor got it fixed, thanks for your help !

**Comment by agarioBotDev** [comment]
@pulviscriptor got it fixed
