### ISSUE TITLE
"Failed to get token!"

### ISSUE THREAD

**Issue by ElieeCh** [pulviscriptor/agario-client#135]
Does anyone know how to fix this problem ?
I already updated the agario-client.js with the new code but It cant seem to fix the whole problem.
Everytime I use fb bots I get the same prob "Failed to get token!" but the normal bots the small ones work perfectly.

**Comment by pulviscriptor** [comment]
Can you provide more info? There is debug output in https://github.com/pulviscriptor/agario-client/blob/master/examples/auth_token.js#L21
Can you show it?

**Comment by SrNicolas** [comment]
the cookies justo don't work, common sense, agar.io madre somethin, so almost all the cookies expire

**Comment by ElieeCh** [comment]
![tok](https://cloud.githubusercontent.com/assets/18157373/14212826/bcc3da2c-f802-11e5-9caa-0806b5a4c946.PNG)

I edited it with the one that you have but it still doesn't work..

**Comment by pulviscriptor** [comment]
@ElieeCh 
You need to launch that and show us what it will tell you.

**Comment by ElieeCh** [comment]
![here](https://cloud.githubusercontent.com/assets/18157373/14213880/35919458-f808-11e5-98d1-61c831bfa6f0.PNG)

that's everything it tells me and after that all of the bots work except for facebook ones

**Comment by SrNicolas** [comment]
BECAUSE the cookies expired, get new cookies

**Comment by ElieeCh** [comment]
Alright, think you're right. Thanks for helping

**Comment by pulviscriptor** [comment]
@ElieeCh
If it helps, then close issue. If not, then i'd like to look more on this, for some reason you don't have request error/HTTP code/redirect URL but no token received.
If this is expired cookies then it should have HTTP code and redirect URL.
