### ISSUE TITLE
 Facebook bots does not work

### ISSUE THREAD

**Issue by LostCodesy** [pulviscriptor/agario-client#137]
Hello pulviscriptor,
Me Facebook bots coded but **agar.io-client Facebook bots 5 days ago fixed**, agar.io-client Facebook bots must update. We are need agar.io-client working Facebook login.

Good Work!

**Comment by pulviscriptor** [comment]
Make sure you are using version 1.3.3
If you do, then this is something new.

**Comment by philw1508** [comment]
I think he is only Not get Tina any cookies because These are updated or banned

**Comment by philw1508** [comment]
**GETTING**

**Comment by LostCodesy** [comment]
Sorry its new error, i m using agar.io-client 1.3.3, need an update in agar.io-client Facebook clients. Thank you for help.

**Comment by pulviscriptor** [comment]
@LostCodesy
Do you have same problem as here? https://github.com/pulviscriptor/agario-client/issues/135
Is token generated for you? If not then do you have request error/HTTP code/redirect URL?

**Comment by LostCodesy** [comment]
Its not, **token working but clients not Facebook**, everything is correct, clients not using-used token.
agar.io-client token using error available.

**Comment by LostCodesy** [comment]
and an error C:\Users\x\Desktop\agarmaster\node_modules\agario-client\agario-client.js:5
30
                throw e;
                ^
TypeError: Cannot read property 'name' of undefined

**Comment by pulviscriptor** [comment]
Okay, i'm not sure what is wrong about facebook there. Don't know if i can help you.
>and an error

Line 530 throws crashed events errors https://github.com/pulviscriptor/agario-client/blob/master/agario-client.js#L530
There is problem in your code.

**Comment by LostCodesy** [comment]
Hey all problems solved, need agar.io-client v1.3.3 for Facebook clients, name function in error "'name' of undefined" no problem its a confusion.

Agar.io-client now all functions working, very successful, several features can be added example free coin event, thank you for help and project source.
Good Work! Perfect Agar.io API project! Its very legal project!

**Comment by pulviscriptor** [comment]
But initially i asked did you upgrade to 1.3.3 and you told me you did.
Oh well, if its fixed, then close issue.

**Comment by LostCodesy** [comment]
No, im first tested but confusion. :(
