### ISSUE TITLE
getPartyServer can't request a proper `getToken`

### ISSUE THREAD

**Issue by l0oky** [pulviscriptor/agario-client#14]
I am trying to use

```
AgarioClient.servers.getPartyServer({party_key: player.party_key}, function(srv){...})
```

But I get this error from AgarioClient :

```
Failed to request server(error = WRONG_HTTP_CODE, error_source = null,
	res = {
		"readable": false,
		"httpVersionMajor": 1,
		"httpVersionMinor": 1,
		"httpVersion": "1.1",
		"complete": true,
		"_pendingIndex": 0,
		"upgrade": false,
		"url": "",
		"statusCode": 404,
		"statusMessage": "Not Found",
		"_consuming": true,
		"_dumped": false
	})
```

My party_key looks like this `#Q4THE`.

Agar.io devs probably changed something..

**Comment by KristophPOL** [comment]
for me works fine but i have something like this 

AgarioClient.servers.getPartyServer({party_key: keyparty}, function(srv) {.....

where 

var keyparty = 'Q4THE';

**Comment by l0oky** [comment]
Yeah, works great.

A small feature would be nice to remove hashtag.

https://github.com/pulviscriptor/agario-client/blob/master/servers.js#L108

`data: opt.party_key.replace('#',''),`

**Comment by pulviscriptor** [comment]
Now keys accepted as:
- Q4THE
- #Q4THE
- http://agar.io/#Q4THE
- everythingBeforeHashtagIsIgnored#Q4THE

**Comment by AmazingGamerBoy** [comment]
Anyone willing to help me create an agario suicide/feeder bot with over 150 bots? This needs to be a local script. It would be fine to edit another script such as pulviscriptor's. Will pay a bit of money if you want (but just a bit). Add me on skype to talk about this: Agario-Lord
My GitHub Account: AmazingGamerBoy
