### ISSUE TITLE
Sniffing Packets

### ISSUE THREAD

**Issue by MasonBurdette** [pulviscriptor/agario-client#142]
Currently I am creating my own client implementation in Node.JS for Slither.io. I am wondering how would I sniff the packets being sent to the WebSocket server. I have found connection, init, and spawn from the client code, but I want to know how to sniff.

**Comment by philw1508** [comment]
U can sniff with wireshark... this is all i know

**Comment by pulviscriptor** [comment]
@MasonBurdette
When i was in your place i made [agario-devtools](https://github.com/pulviscriptor/agario-devtools) where i have repeater/recorder to analyze packets and debug client. I used agar's `connect()` function to connect into tools, but if slither don't have anything like that you may need to modify js scripts.

**Comment by MasonBurdette** [comment]
@pulviscriptor I've heard of wireshark more often recently, but how would i use it?  i want to see raw packets being sent.

**Comment by philw1508** [comment]
@MasonBurdette i only heard that u can sniff the traffic but I dont know if it sniffs Pakets :/

**Comment by pulviscriptor** [comment]
@MasonBurdette
You can use wireshark, but websockets uses frames for transferring data, and client->server frames are masked (data shuffled) and some data could be sent in more than one frame and frames contain not only your data but some of service information too. Here is format of frame from RFC:
>       0                   1                   2                   3
      0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
     +-+-+-+-+-------+-+-------------+-------------------------------+
     |F|R|R|R| opcode|M| Payload len |    Extended payload length    |
     |I|S|S|S|  (4)  |A|     (7)     |             (16/64)           |
     |N|V|V|V|       |S|             |   (if payload len==126/127)   |
     | |1|2|3|       |K|             |                               |
     +-+-+-+-+-------+-+-------------+ - - - - - - - - - - - - - - - +
     |     Extended payload length continued, if payload len == 127  |
     + - - - - - - - - - - - - - - - +-------------------------------+
     |                               |Masking-key, if MASK set to 1  |
     +-------------------------------+-------------------------------+
     | Masking-key (continued)       |          Payload Data         |
     +-------------------------------- - - - - - - - - - - - - - - - +
     :                     Payload Data continued ...                :
     + - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +
     |                     Payload Data continued ...                |
     +---------------------------------------------------------------+

Its hard even look at it. At least for me. 
So i do not recommend use wireshark for that. Find some extensions for your browser that can show webscokets data or modify game's scripts to output packets.

**Comment by DeepSnowNeeL** [comment]
Wireshark already handle websockets and show the payload unmasked I think.
But you should override the native buffer send in the dev console so you
can output every sent data to console.log it would be easier

Le ven. 8 avr. 2016 08:10, pulviscriptor <notifications@github.com> a
écrit :

**Comment by MasonBurdette** [comment]
Thank you for all the help, I think I understand more now.
