### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by kurama129** [pulviscriptor/agario-client#146]
plz tell how to install in detailed instructions and doesnt it have a code to install andn tampermonkey
if not just give how to make it work

**Comment by pulviscriptor** [comment]
This is not bot, this is library for agar.io protocol. If you know Node.JS/JavaScript language then you install it via `npm install agario-client`, read documentation https://github.com/pulviscriptor/agario-client/blob/master/README.md and write your own code.
If you don't then you're in the wrong place.

**Comment by kurama129** [comment]
i did make one but only normal are coming for facebook it says failed to get token

**Comment by philw1508** [comment]
Dude.. how often does i have to say it?? ALL LEAKED ACCOUNTS ARE BANNED FROM $MONEY$CLIP$

**Comment by kurama129** [comment]
can you help me make it work at least trying with my one account

**Comment by philw1508** [comment]
Set the cookies of YOUR facebook account in and then log off ur Account from agario and then run the feeder

**Comment by kurama129** [comment]
not working do you have your script that is working

**Comment by kurama129** [comment]
or can you say how to get  token
for agario fb

**Comment by sejo153** [comment]
@kurama129 you dont have to acces the token, just get COOKIES!!!
