### ISSUE TITLE
FB botz work or not

### ISSUE THREAD

**Issue by problemsofworld** [pulviscriptor/agario-client#149]

**Comment by pulviscriptor** [comment]
Tested to be sure. Both examples `auth_token.js` and `basic.js` with FB token works great. 
Client obtain 60+ mass after spawn.

**Comment by philw1508** [comment]
@pulviscriptor i have Gotten 40 working tokens but if my bots Spawn i only get like 1 of 1000 bots with facebook mass and It's always with the Same skin (the bot that Join with facebook mass)

**Comment by pulviscriptor** [comment]
@philw1508
So its something not related to client. Tokens are correctly sent to server and server understands them since examples is working. 
Why server ignores your tokens is some other question that most probably can't be fixed by client.

**Comment by MasonBurdette** [comment]
@pulviscriptor is right
Also many leaked accounts have stopped working. (I suppose they're banned)

**Comment by philw1508** [comment]
@MasonBurdette Yes I know... leaked accs by stavj or freeagarbots.tk.... but I got New cookies by random People 2 days ago so I dont think that are banned now....

**Comment by kurama129** [comment]
btw stavj doent know js hes just a scammer he took the bots from me and happy

**Comment by MasonBurdette** [comment]
Hm

PS at first those accounts were Chris Pierce's, I had them before they were leaked.

**Comment by philw1508** [comment]
@MasonBurdette how could he have so many?? I had like 70k lines only with facebook cookies... Did He hack any database?

**Comment by MasonBurdette** [comment]
An extension stole them
agarioinfinity.tk

**Comment by Nick8fr32** [comment]
Chris Pierce stole them from MrSonic. MrSonic leaked all the acc from his script on his web site

**Comment by MasonBurdette** [comment]
@Nick8fr32 incorrect, im friends with them both (theyre friends too) and we all shared the cookies, they did originate from Chris Pierce...

**Comment by philw1508** [comment]
@MasonBurdette but it couldnt be possible that his extension stole 1500 accounts...

**Comment by pulviscriptor** [comment]
Guys, can you move somewhere else please? 
We have 14 watchers and we all receive email on every your useless message. 
Please talk only about bugs here.
Thank you.
