### ISSUE TITLE
slither.io client ?

### ISSUE THREAD

**Issue by agarioBotDev** [pulviscriptor/agario-client#150]
hello,

will you make a slither.io client ? Because maybe i will do one and some help would be great :)

greats,
david

**Comment by MasonBurdette** [comment]
I am in the situation..
www.github.com/masonburdette/slither-client

**Comment by agarioBotDev** [comment]
@MasonBurdette to make it public just allows noobs to get free bots. This will destroy the game like agar.io is destroyed. I will help you, but only if you don't publish it.

**Comment by agarioBotDev** [comment]
@MasonBurdette is there a wiki already or not ? cannot find one

**Comment by pulviscriptor** [comment]
@agarioBotDev
I am not making slither.io client and not planning to do any. 
I made `agario-client` for learning, don't see anything new i can learn making slither client so i'm not interested in it.

**Comment by MasonBurdette** [comment]
@agarioBotDev skype?  i code agar bots too (without agario-client) and an working in slither.

**Comment by agarioBotDev** [comment]
@MasonBurdette yes, my site is: d-bots.com, but i will not make my skype public - just write an email to agarbotsDavid@gmail.com then i can give you my skype.
