### ISSUE TITLE
help me not working

### ISSUE THREAD

**Issue by kurama129** [pulviscriptor/agario-client#151]
i got 2token help me but no fb bots im using stavj script just adding new cookies to fbmanger only the normal comes

**Comment by hassanila97** [comment]
I have the same problem... I get tokens but I think Agar.io changed some FB authentication again...  let us know @pulviscriptor

**Comment by pulviscriptor** [comment]
Just tested `examples/auth_token.js` and `examples/basic.js` and everything still works. There is no problem in `agario-client`.
