### ISSUE TITLE
Cookies not working

### ISSUE THREAD

**Issue by googleboy360** [pulviscriptor/agario-client#153]
I have a issue where ti says failed to get tokens but i updated the tokens and it changes each time when person login in or log out of facebook.my friend says it expires in 60 days.But i notice how only xs: changes everything else  the same

**Comment by googleboy360** [comment]
is there a way to keep the cookies from changing?

**Comment by googleboy360** [comment]
also who is willing to help me out on this ill give one or two private bots tha are levels 75 and level 5 with skin

**Comment by problemsofworld** [comment]
ya if delete  cookies wanna share bro how many  cookies u got ?

**Comment by pulviscriptor** [comment]
Cookie and tokens works fine, this is not issue, please don't spam peoples emails 
https://github.com/pulviscriptor/agario-client/issues/149#issuecomment-209753520
