### ISSUE TITLE
partner for d-bots.com ?

### ISSUE THREAD

**Issue by d-bots-client** [pulviscriptor/agario-client#155]
hey pulviscriptor,

I'm searching for a partner or developer for my site d-bots.com. The agar.io bots system is finished and working wothout any erros, but i stuck at the slither.io bots....allthough i don't have enough time for my site d-bots.com (support etc.), in order to change that i'm searching for a partner or developer....

PS: the site is a hobby but it also makes a bit of money, so if you are interested... ;)
greats,
david

**Comment by pulviscriptor** [comment]
Not interested.
