### ISSUE TITLE
TypeErrors

### ISSUE THREAD

**Issue by tweenkapy** [pulviscriptor/agario-client#163]
Hi, some errors

[TypeError: Cannot assign to read only property 'type' of reserved fields must be empty]

[TypeError: Cannot assign to read only property 'type' of continuation frame cannot follow current opcode]

**Comment by Sonicmaster13** [comment]
I'm pretty sure this is part of WebSocket.js in the 'ws' library that Agario-Client uses to connect to the Agario server

go into the node_modules folder, go into ws, go into lib, open WebSocket.js

Look for: event.type =
Delete the lines that say that(their should be 2)
