### ISSUE TITLE
fb bots don't connect with mass

### ISSUE THREAD

**Issue by Wartoz** [pulviscriptor/agario-client#168]
I got 400+ working tokens but only 1 of fb bots show up in game the rest are normal bots. I updated agario-client but it didn't fix it :/

**Comment by ravyn120** [comment]
Try making your own script also your cookies might be banned

**Comment by ravyn120** [comment]
By script script I mean where you list your cookies. Since you probably use the free one

**Comment by DaAwesomeRazor** [comment]
how are you using your cookies. You have to use 1 cookie per bot. Here is an example of a simple cookie manager.

`var tokens = []//Cookie aray goes here

//Then you set your auth token to
this.client.authToken = getToken(this.bot_id)

function getToken(bot_id) {
return tokens[bot_id]
}`
