### ISSUE TITLE
FB BOTS PLS HELP

### ISSUE THREAD

**Issue by Wawy123** [pulviscriptor/agario-client#171]

**Comment by Wawy123** [comment]
OK i have 3440 fb cokies and i nedd some fb bots!
i dont  know how to make it so please can somebody help???????
pls
pls

**Comment by Nick8fr32** [comment]
I Can help u if i get 400 cookies @Wawy123

**Comment by Wawy123** [comment]
ok no problem but i dont know if cookies are baned or not

**Comment by Nick8fr32** [comment]
Were did u get Them? @Wawy123

**Comment by Wawy123** [comment]
i had cookies from razor fb bots but i dont know how to run it video: https://www.youtube.com/watch?v=SFg9tmWBs7w i found his cloud9 and download his bots

**Comment by Nick8fr32** [comment]
We Can test it later I'm in school right now

**Comment by Nick8fr32** [comment]
@Wawy123 I get home in about an hour

**Comment by Wawy123** [comment]
i must go

i come back after 1h

**Comment by Wawy123** [comment]
i too come to home in about 1 hour :)

**Comment by Wawy123** [comment]
hello

**Comment by Nick8fr32** [comment]
@Wawy123 get on [discord](https://goo.gl/bAer3k)

**Comment by Wawy123** [comment]
what is this for clan???

**Comment by Nick8fr32** [comment]
do i can help u with bots @Wawy123

**Comment by Wawy123** [comment]
yea

**Comment by Nick8fr32** [comment]
then join the discord!

**Comment by Wawy123** [comment]
i join

**Comment by pulviscriptor** [comment]
@Wawy123 
I don't know what was the issue here but if its solved - close it.

**Comment by Wawy123** [comment]
issue is to i need help with fb bots i have got 180 working fb cookies so pls help!!!1

**Comment by Wawy123** [comment]
pls help

**Comment by pulviscriptor** [comment]
@Wawy123 
This repository is not about bots or FB, its about client for game, its protocol and API. On protocol level FB tokens are correctly sent to server and server understands them. 
You need some place where peoples code bots and FB and stuff. This is wrong place. Low chances that you will find help here.
For example here is place about bots https://github.com/davidmann4/ogar-feeder-bot maybe somebody there can help you.
