### ISSUE TITLE
Agario client less cpu = 400 bots!

### ISSUE THREAD

**Issue by MuccaDiocan** [pulviscriptor/agario-client#173]
https://www.youtube.com/watch?v=DxPyYdbvIpY&feature=youtube_gdata
here you go :)

**Comment by Nick8fr32** [comment]
I have 400+ bots and i dont use vps or anything

**Comment by pulviscriptor** [comment]
Oh guys, when you stop creating issues that not issues at all. Lots of peoples receiving garbage emails because of this. 
Please move to some chats/forums/social networks, don't create useless issues.
