### ISSUE TITLE
reconnect

### ISSUE THREAD

**Issue by kurama129** [pulviscriptor/agario-client#175]
mr pulvis criptot add me on skype or add a reconnect code in script thx

**Comment by pulviscriptor** [comment]
After disconnect you can call `client.connect(server, key)` and that will re-connect you to server.

**Comment by kurama129** [comment]
which line

**Comment by kurama129** [comment]
can you add and send
me

**Comment by kurama129** [comment]
and is there a way to hire you

**Comment by pulviscriptor** [comment]
>which line

Are you using some script made by somebody somewhere? You probably should ask author of that script to make it for you. This is wrong place.
