### ISSUE TITLE
[Need Help] Multiple Client

### ISSUE THREAD

**Issue by MasonBurdette** [pulviscriptor/agario-client#176]
I have the basics done already (split,feed,follow mouse). I see where in examples/multiple.js it makes a `new ExampleBot` and I have made my own `bot.client.split()` and `bot.client.eject()`. All of the client data is streamed through a websocket connection, which is great. Now here is my problem, how would I make this script compatible for multiple users? So if one client/connection's `x` and `y` position are different or split/eject values are different, only his bots would do that. I hope someone has an answer to help me, thank you in advance.

P.S., would it be possible, just to make multiple servers run, and make a server finder to find the next open server (on ws open `serverInUse = true` and on ws close `serverInUse = false`.) then it would check each server for availability..? im not sure if that is possible, but i'd rather have an elastic server.

**Comment by MasonBurdette** [comment]
Since nobody has replied, I thought you might not understand what I am saying.  Here is a succinct example.

Someone with the UUID "1234" spawns in bots - they spawn in and follow **his** mouse positions
Someone with the UUID "4321" spawns in bots - they spawn in and follow **his** mouse positions,
Someone with the UUID "4321" splits his bots - only **his** bots split,
etc.

So what I am asking is how would I accomplish this?  Any answers are appreciated greatly.

**Comment by pulviscriptor** [comment]
Your question is more about coding in general than about `agario-client`. You need to find place where coding-newbies can get help.

**Comment by hassanila97** [comment]
@MasonBurdette well... just one thing  dont use agario-client  if you're planning to sell bots...  its a very stupid idea.. also I thought you were a coder dude  LOL

**Comment by MasonBurdette** [comment]
@hassanila97 Nah I'm just asking it here. I send raw websockets with my own client.

**Comment by MasonBurdette** [comment]
Could I make an array of all UUIDs, and define [UUID].bot.client?

**Comment by MasonBurdette** [comment]
I figured it out ;)
