### ISSUE TITLE
Bugs..

### ISSUE THREAD

**Issue by ElieeCh** [pulviscriptor/agario-client#177]
After last update:

1- The amount of bots that is spawning is always showing 0 even though some of the bots are working.

2- This error is showing: Cannot read property 'name' of undefined

@pulviscriptor Hope you help me. Thank you. 
 
Also anyway that knows how to fix them, please comment down below how. Thanks :)

**Comment by MasonBurdette** [comment]
these are agar-feeder-bot related issues, please close this and open it at davidmann's repo.

**Comment by ElieeCh** [comment]
But they only happened since pulviscriptor updated his repo ... and David didn't touch his. Plus david isn't replying lately so pulviscriptor might help me ._. Anyway I got this new error also.. I don't know what's happening. 
![capture](https://cloud.githubusercontent.com/assets/18157373/14939432/8a3aeb08-0f14-11e6-9237-c597892f9261.PNG)

**Comment by MasonBurdette** [comment]
@ElieeCh thats called a packet error, some say it is caused from bad proxies.

**Comment by ElieeCh** [comment]
Does it matter if the proxies are transparent or anonymous or elite ? 

Also most of mine are pretty fast.. I've already checked them with 3 different programs...

**Comment by ElieeCh** [comment]
Okay, so I was using a modified version ogar-feeder-bot made by david, now that I've tried using his version the only error left is this one

![capture](https://cloud.githubusercontent.com/assets/18157373/14939950/58edb888-0f2c-11e6-873c-1ddff2b56dd8.PNG)

**Comment by ElieeCh** [comment]
Edit: It looks like the error that I see (from unexpected server response <400>) is caused by my proxies because I'm using HTTP ones also I don't know why they're causing this error even though most of them are working fine.
