### ISSUE TITLE
Help please!

### ISSUE THREAD

**Issue by ElieeCh** [pulviscriptor/agario-client#178]
I'm trying to install a new http proxy agent in the bot that david created. I know you're not responsible for it and I have to ask him for help but lately david isn't replying and I personally don't know anyone that can code better than you.
So I installed the code on this repo https://github.com/nodejitsu/node-http-proxy and changed the https-proxy-agent in feeder.js to the new one.
But I keep getting this error:
![capture](https://cloud.githubusercontent.com/assets/18157373/14940413/056e9ec8-0f42-11e6-9536-a37c2df5db3c.PNG)

Can you please tell me, what am I supposed to do ?
I would really appreciate your help or anyone else! Thanks.

**Comment by pulviscriptor** [comment]
Honestly i do not know how agents works.
You probably should try ask author of your agent, he should know better how they working.

**Comment by ElieeCh** [comment]
Okay, thanks for replying tho ! :)
