### ISSUE TITLE
Getting almost none fb bots with 700 working tokens.

### ISSUE THREAD

**Issue by SrNicolas** [pulviscriptor/agario-client#179]
In complete I don't use agario-client, but i use the send token function, Did agar.io do something? Because I get 20fb bots only and disabling the token send, i get 300-400

**Comment by Nick8fr32** [comment]
I don't think they changed anything because I used my bots before I only have 20 cookies and I got like 15-19 fb bots @SrNicolas

**Comment by SrNicolas** [comment]
Hmmm, strange

Nick, are you using ogar-feeder-bot, because my ogar bot is glitched too, maybe the accounts, idk

**Comment by Nick8fr32** [comment]
@SrNicolas Yea I use davidmanns with some fixes and my script works fine

**Comment by SrNicolas** [comment]
strange af, cuz I got 700 working tokens without repeats lol

**Comment by Nick8fr32** [comment]
And they are not banned or anything??

**Comment by SrNicolas** [comment]
nope

**Comment by SrNicolas** [comment]
I don't think the users of my extensions are stupid enough to get banned their acc

**Comment by Nick8fr32** [comment]
XD maybe. But then its probably just a error in ur code?

**Comment by SrNicolas** [comment]
nope, cuz its not working with the leaked ogar with fb

**Comment by Nick8fr32** [comment]
That is very weird because my script work perfect but in only have 20 cookies

**Comment by SrNicolas** [comment]
nick add me on skype, ill give some more

**Comment by SrNicolas** [comment]
skype : nicolasdelito

**Comment by Nick8fr32** [comment]
get in my [discord](https://goo.gl/bAer3k)

**Comment by Nick8fr32** [comment]
@SrNicolas can we solve this tomorrow i need to go now

**Comment by Wartoz** [comment]
nick8fr32 got 1,500 working token no duplicate my skype iTwiGXDev and my bots works fin with eat pellets mode too

**Comment by Wartoz** [comment]
nick8fr32 i'm on your discord

**Comment by pulviscriptor** [comment]
Please stop spamming here.
