### ISSUE TITLE
Websocket throwing error

### ISSUE THREAD

**Issue by EptunLP** [pulviscriptor/agario-client#18]
So, i have created bots that will go inside you, agario minions. Whenever i connect to a server on browser, it sends websocket to server saying ip and key, then one bot is created and then disconnected.

Image:
![image](https://cloud.githubusercontent.com/assets/8792171/9982078/c811912e-5fcf-11e5-9161-ed73b25f4e3c.png)

**Comment by pulviscriptor** [comment]
Okay, this is second report of this. https://github.com/pulviscriptor/agario-client/pull/16
And as i see, it is caused by user's code that tries to send data before connection established. 
*I assume you used .moveTo() before "connected" event
I will implement checks inside lib so functions will just return false if connection is not ready.
I need some time for fixes.

**Comment by EptunLP** [comment]
I have even tried to spawn without .moveTo() event

the code is:
var WebSocketServer = require('ws').Server
  , wss = new WebSocketServer({ port: 8080 });
var AgarioClient = require('./agario-client.js'); //in your code you should do require('agario-client')

var http = require('http');

var client = new AgarioClient('worker'); //create new client and call it "worker" (not nickname)
var interval_id = 0; //here we will store setInterval's ID

client.debug = 1; //setting debug to 1 (avaialble 0-5)

client.on('connected', function() { //when we connected to server
    client.log('spawning');
    client.spawn('agario-client'); //spawning new ball
});

wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(message) {
    var msg = JSON.parse(message);
    if(msg['action'] === 1) {
       //console.log(msg);
       client.connect(msg['targetIp'], msg['targetRoom'])
       console.log();
    }
  });
});

And it says disconnected

![image](https://cloud.githubusercontent.com/assets/8792171/9982167/ad2db088-5fd2-11e5-9e63-03fc2ba4cacb.png)

**Comment by pulviscriptor** [comment]
EptunLP,
Are you sure that you use valid key for `client.connect()` function?
If i replace call in `example.js` to 

    client.connect('ws://' + srv.server, 'INVALID_KEY'); 

I have exact same result. Disconnect after connect.
Please check that you receive key from same IP that you connect from and you receive new key before each connection to server.
Easiest way is to use `AgarioClient.servers.`. Check how `example.js` uses `AgarioClient.servers.getFFAServer()`

**Comment by EptunLP** [comment]
Im pretty sure that the key for the ip is valid, because i get the key straight from agario client side code, it sends through websocket the same ip and key it connects to, anyways i have no idea why it shows error.

**Comment by pulviscriptor** [comment]
EptunLP,
Fixed code, now you can safe use `moveTo()` before connection. Update your agario-client.
But i think that your problem is in keys.

**Comment by EptunLP** [comment]
I use this code to send details to the server:

e.targetRegion = In + Yn, e.targetIp = t, e.targetRoom = n, cn.send(JSON.stringify(e))

Maybe the code is bugged, which i highly doubt. If there is any other way of getting client side target room, would be happy if you would tell me

**Comment by pulviscriptor** [comment]
EptunLP,
Since key implementation i know only "bruteforce" method. But agar.io can ban you for that.
Or you can use parties. Then you need IP, port and server key is same as party ID. You can re-use it multiple times from any IP.

**Comment by EptunLP** [comment]
Yeah, it looks like the problem is with server key, i have no idea whats the variable of the party token from the client code, if you would know, thanks!

**Comment by pulviscriptor** [comment]
EptunLP,
Lazy method:
`document.getElementsByClassName('partyToken')[0].value.split('#')[1]`
Correct method:
I'm too sleepy for investigating.

**Comment by pulviscriptor** [comment]
Okay, here is code of agar.io's implementation.

        function kb(a) {
        ga(":party");
        e$$1("#helloContainer").attr("data-party-state", "4");
        a = decodeURIComponent(a).replace(/.*#/gim, "");
        bb("#" + d.encodeURIComponent(a));
        e$$1.ajax(ea + "getToken", {
            error : function() {
                e$$1("#helloContainer").attr("data-party-state", "6");
            },
            success : function(b) {
                b = b.split("\n");
                e$$1(".partyToken").val("agar.io/#" + d.encodeURIComponent(a));
                e$$1("#helloContainer").attr("data-party-state", "5");
                ga(":party");
                Ma("ws://" + b[0], a);
            },
            dataType : "text",
            method : "POST",
            cache : false,
            crossDomain : true,
            data : a
        });
    }

where `a` is `window.location.hash`.
So you're safe to use `decodeURIComponent(window.location.hash).replace(/.*#/gim, "")`.
Now i need to sleep. Bye.
