### ISSUE TITLE
Help !

### ISSUE THREAD

**Issue by ElieeCh** [pulviscriptor/agario-client#181]
Again sorry for interrupting... I don't know if you can answer this question but I can always try 

Some of the proxies worked after I fixed the problem and some of them still gives me an error do you think there is anyway to identify them so I can remove them from my proxy list (the one that gave me the error). Thanks!

**Comment by kurama129** [comment]
yea use a proxies checker and get list of dead and live proxies of your list

**Comment by Nick8fr32** [comment]
@kurama129 no that doesn't help the proxies can be banned and the don't work we need a way to delete the banned and dead proxies for the proxy.txt file

**Comment by ElieeCh** [comment]
No, what I meant to say is that even if the proxies aren't dead they still won't work sometimes (Yes I checked them with 3 programs.) so how am I supposed to know which ones are working when it's telling me they're all alive.. ?

**Comment by pulviscriptor** [comment]
@ElieeCh 
Please move to some other place where peoples talk about proxies. Lots of peoples receives emails with every your message here.
`agario-client` is about protocol of game, not proxies and fb and stuff related to bots.
