### ISSUE TITLE
Failed to get token! HTTP code: 302

### ISSUE THREAD

**Issue by funfrfr** [pulviscriptor/agario-client#182]
Failed to get token! HTTP code: 302
anyone know how to fix this i think because the XS changing when I logout so it cant get the token

**Comment by pulviscriptor** [comment]
Check your cookies. Probably you setting them to wrong values.
If you do know that you setting them to wrong values, then `agario-client` can't get correct cookies for you.

**Comment by funfrfr** [comment]
i fixed it and it succeeded i get the token but i didn't see the facebook bots in game what should i do
(maybe i should do something with the token but i dont know what)

**Comment by pulviscriptor** [comment]
@funfrfr 
Test your own cookies from your own facebook account, will it work?
If it does, then you do everything correctly but `agario-client` can't help you with stolen cookies
https://github.com/pulviscriptor/agario-client/issues?utf8=✓&q=label%3Afacebook+
