### ISSUE TITLE
Facebook Bots Not Working

### ISSUE THREAD

**Issue by LostCodesy** [pulviscriptor/agario-client#183]
Hey Hello,
Me agar.io bot  in facebookManager.js using but maximum 5 facebook bots to me ?
I have 500 facebook cookie available help me.
Good Work!

**Comment by Nick8fr32** [comment]
maybe ur facebook cookies dont work

**Comment by pulviscriptor** [comment]
@LostCodesy 
Welcome to the army of facebook peoples
https://github.com/pulviscriptor/agario-client/search?p=1&q=fb&type=Issues&utf8=✓
https://github.com/pulviscriptor/agario-client/search?utf8=✓&q=facebook&type=Issues
Your problem is not fixable by `agario-client`. You 're in the wrong place.
