### ISSUE TITLE
help

### ISSUE THREAD

**Issue by kurama129** [pulviscriptor/agario-client#184]
is there a way to put less load on cpu but maintain a high ratio of bots and reconnect code plz

**Comment by ravyn120** [comment]
Make a new feed bot using agario-client with only finding x and y and pos of cell a and mouse and some way to receive it from agario the for reconnect maybe make a bot counter and check if it goes down if it goes down client.spawn

**Comment by pulviscriptor** [comment]
@kurama129
https://github.com/pulviscriptor/agario-client/issues/161#issuecomment-213363738
