### ISSUE TITLE
pulvis scriptor help

### ISSUE THREAD

**Issue by kurama129** [pulviscriptor/agario-client#185]
ok all i need is to reduce cpu load is there a way to do that and btw if cpu is full will bots lag

**Comment by pulviscriptor** [comment]
I can't do anything with CPU load.

**Comment by kurama129** [comment]
ok how to cofig max bots instead of 9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
