### ISSUE TITLE
Facebook account requestFBToken Proxy using

### ISSUE THREAD

**Issue by LostCodesy** [pulviscriptor/agario-client#187]
Hello,
Help me, @pulviscriptor Agar.io is patched, requestFBToken for max 2 account in max 1 ip.

Learn to me please requestFBToken.agent 
Good Work.

**Comment by MasonBurdette** [comment]
Maybe `examples/auth_token.js` will help

**Comment by Nick8fr32** [comment]
lol i just tested with 3 acc on same ip and it worked fine???

**Comment by pulviscriptor** [comment]
@LostCodesy 
Check `examples/socks.js` there you can see how to use agents.

**Comment by LostCodesy** [comment]
@pulviscriptor yes but I think I need to https ?

**Comment by pulviscriptor** [comment]
@LostCodesy 
For client i tested only SOCKS, i'm sure SOCKS will work for your needs too. I don't know about HTTP/HTTPS, you need to test yourself to find out.

**Comment by SrNicolas** [comment]
Lol, I got 700 working tokens, all requested fine and when my bots use it, I get the bots, so u might want to change IP or something

**Comment by LostCodesy** [comment]
@SrNicolas me have 5,000 working proxies but not working disconnect in agario.

Please give me a working facebook bot and me give you Facebook Cookie Checker , Oke?

**Comment by SrNicolas** [comment]
Ok

Add me to skype and we talk: nicolasdelito

**Comment by LostCodesy** [comment]
@SrNicolas i added, my skype = greenskypark

**Comment by LostCodesy** [comment]
@SrNicolas Add me to skype
