### ISSUE TITLE
Agario updated, bots no longer working.

### ISSUE THREAD

**Issue by easyrider81** [pulviscriptor/agario-client#190]
title says it all.

**Comment by Lukkez** [comment]
It's agar-expose fault

**Comment by DaAwesomeRazor** [comment]
This has nothing to do with agario bots. This client still works. Plus, bots are so easy to fix. It took 5 mins for me to figure out :D

**Comment by pulviscriptor** [comment]
@easyrider81
`agario-client` still works, but this might be beginning of the end of `agario-client`. I can't do much with their new script.

**Comment by anonymousxxx02** [comment]
@DaAwesomeRazor can you please help me to fix bots
