### ISSUE TITLE
Hey Pro pulviscriptor

### ISSUE THREAD

**Issue by LostCodesy** [pulviscriptor/agario-client#194]
**Hey bro you are pro pulviscriptor !!! 
Other developers bad and know very little :/

Need you pro for new agario-client !!!

Please, Please, Please  You continuation for agario-client !!! 

We are need YOU ! We are love you !!! You are pro for we are !!!!! 

Please continuation! #Continuation #NoEndForAgarioClient 
# continuation #continuation

We are sad !!!!**

**Comment by ghost** [comment]
update client  agario is dying no bots #save agario bots now working on new client

**Comment by Hazardous16** [comment]
Sounds cool ProblemsofWord

**Comment by mbm3** [comment]
@problemsofworld we should skype soon what's yours?
mine is masonthegreifer

**Comment by pulviscriptor** [comment]
@LostCodesy 
I just can't do it. It is like guy who know how to fix car, need to fix space rocket. 
That virtual machine works on very low level and that beyond of what i know and what i can do.
We need new sheriff in town, who will manage and fix it all and make new client.

**Comment by LostCodesy** [comment]
@pulviscriptor agario-client not 100% fixed only fixed websocket open others working.

Example getPartyServer working too working function in agario-client.

Something must try
