### ISSUE TITLE
ITS NOT PATCHED! - Working FB, spawning, updating position, etc!

### ISSUE THREAD

**Issue by ghost** [pulviscriptor/agario-client#196]
I have developed a version of agario-client which fully works-- facebook, spawning, going towards a position, you name it!

**Comment by Nick8fr32** [comment]
@XtremePlayzCODE are u gonna share or make a new client or something??=)<3

**Comment by ghost** [comment]
@Nick8fr32 will share when someone finds out a new fix.

**Comment by Nick8fr32** [comment]
u just said that u had a fix

**Comment by wartoz** [comment]
bots patched for ever

**Comment by ghost** [comment]
@Nick8fr32 to see if they have more effecient fixes.
@Wartoz Nope. Not possible to be patched forever

**Comment by Nick8fr32** [comment]
@XtremePlayzCODE it is easy for them to patch bots and they can patch them forever

**Comment by ghost** [comment]
theres something called rainbow code

**Comment by yario-o** [comment]
@kurama129 you don't understand the "raimbow code" ils just a graphic...

**Comment by ghost** [comment]
no rune saying by ranibow code bots work etc

**Comment by ghost** [comment]
in youtube are they wrkig

**Comment by wartoz** [comment]
rainbow code is only on his gui

**Comment by ghost** [comment]
how are his bots working

**Comment by ghost** [comment]
@Nick8fr32 Do I need to close down miniclip? -_-

**Comment by ghost** [comment]
# ****MINICLIP DONT KNOW SHIT ABOUT JAVASCRIPT

**Comment by MinersMC** [comment]
Moneyclip*\* lol

**Comment by ghost** [comment]
FUCKING MONEYSLUTS THEY ARE

**Comment by ItzLevvie** [comment]
moneywhore

**Comment by ghost** [comment]
I SWEAR TO FUCKING GOD I WILL FIND ANYONE WHO MADE THE NEW AGARIO UPDATE FUCKING PUT BLEACH IN THEIR RUSSIAN ASS TEA AND SLIT THEIR FUCKING WRISTS IN THEIR SLEEP AFTER CUTTING OFF THEIR DICKS AND MICROWAVING IT AND FEEDING IT TO MY PET GERBIL THEN COVER THEM IN MOTHERFUCKING RUSSIAN TEA HOTTER THAN THE SUN AND RECORD IT

**Comment by Andrews54757** [comment]
@XtremePlayzCODE Calm down. Dont ask why im here as well.

**Comment by glenclark** [comment]
https://github.com/SNSA/agario-client2   ......Maybe this will help you if you get it to work let me know

**Comment by ghost** [comment]
@Andrews54757 Can you please unban me from Ogar Unlmited? LegitSoulja was being a dick and banned me for no reason

**Comment by Andrews54757** [comment]
no, I see why he banned you.
1. You have rage outbursts
2. you spam
3. you offend others
4. you dont follow guidlines
5. profanity
6. you **lie** alot (like finding the client)

What more examples do i have to give? This issue itself is a lie, I have never seen any proof of you developing something and moneyclip completely changed everything including encrypting packets, unique keys, adding ban, and absolutely changing the packets.

I hate it when people lie, and i see it alot in you. I also saw how you lied to **c9** here:https://community.c9.io/t/devs-only-banned/5481. I have eyes everywhere and people report to me things that others do. And you have a really bad reputation.

**Comment by Andrews54757** [comment]
Also note that you are not the only one who is banned. Others are banned as well and because of the new ban policy, ogarUL is actually more peaceful with **REAL** issues and **NICE** people

**Comment by ghost** [comment]
@Andrews54757 When did I have rage outbursts except for here?
When did I lie? It was close to working, but not entirely as I stated.
I'm a fucking man, so I can use profanity. People don't attack ETZesty for profanity.
When did I offend people? They were the ones offending me, and I was throwing back like a man.
When do I spam?
What guidelines?

(p.s. already actually found a fix with an extension and made my own private server, and my 273 subscribers will **FUCK YOUR SHIT UP** (jk, its a joke from some guy on youtube))

**Comment by Andrews54757** [comment]
### I will go through this all

> @Andrews54757 When did I have rage outbursts except for here?

Technically, ALL THE TIME! Should I list them?

> When did I lie? It was close to working, but not entirely as I stated.

Thats lying. Over-exaggerating is kinda lying. You also lied to c9

> I'm a fucking man, so I can use profanity. People don't attack ETZesty for profanity.

Men should have honor, just being a man isnt an excuse. Be a gentleman. 

> When did I offend people? They were the ones offending me, and I was throwing back like a man.

You are the one who offend others first. And even if you dont, If you actually are a man, you should be able to suck it up, not fight back.

> When do I spam?

You posted issues in ogar unlimited that were not relevant, posted simple issues you could have took the time to research on google, and spammed comments by thinking that issues is an area to chat

> What guidelines?

There are clear guidlines here : https://github.com/AJS-development/Ogar-unlimited/blob/master/.github/ISSUE_TEMPLATE.md

> (p.s. already actually found a fix with an extension and made my own private server, and my 273 subscribers will FUCK YOUR SHIT UP (jk, its a joke from some guy on youtube))

Then my 58,000 supporters will F you up.

(people who like this, put the like emoji)

**Comment by ghost** [comment]
@Andrews54757 so... you liked your own post

P.S. It was a joke.

**Comment by DaAwesomeRazor** [comment]
@XtremePlayzCODE Could you add me on skype? santa.gaming

**Comment by ghost** [comment]
ok why...
