### ISSUE TITLE
Free spectator mode

### ISSUE THREAD

**Issue by jashman** [pulviscriptor/agario-client#20]
The official agar.io client has a free spectate mode when you hit the 'q' key, allows you to roam around as a spectator, similar to moving your ball around via moveTo().  Is this on the horizon planned for implementation?

**Comment by henopied** [comment]
couldn't you just do moveTo() after sending opCode 18?

**Comment by jashman** [comment]
@henopied that does indeed work like a charm.  It has different effects on agar.io official servers vs Ogar servers (flat toggle on agar.io vs switch player being spectated on Ogar).

**Comment by pulviscriptor** [comment]
Implemented by https://github.com/pulviscriptor/agario-client/pull/21
