### ISSUE TITLE
FAILED TO GET TOKEN help pls :)

### ISSUE THREAD

**Issue by Shadoweee77** [pulviscriptor/agario-client#200]
I downloaded the freeagarbots.tk script ( fb bots ) and its conecting to my client but: 
at the frame of  bots stats there is something like that: Minions: Offline
I searched everywhere i could but I didint found the fix for that. screenshots:
![zrzut ekranu 47](https://cloud.githubusercontent.com/assets/20088126/16263893/e44c430e-3876-11e6-8069-e01bd3c8dc84.png)
![Uploading Zrzut ekranu (48).png…]()
![zrzut ekranu 49](https://cloud.githubusercontent.com/assets/20088126/16263894/e44da73a-3876-11e6-85ae-0d0449550d95.png)

**Comment by pulviscriptor** [comment]
Your question is not related to `agario-client`. 
But even if it would, development of `agario-client` is closed.
