### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by mbm3** [pulviscriptor/agario-client#201]
deleted

**Comment by DeltaEnemy** [comment]
Did you tested it? I'll try soon.

**Comment by MasonBurdette** [comment]
I haven't yet, but if the algorithm is right, it should just be a simple XOR encryption key that changes after each message.

**Comment by MasonBurdette** [comment]
Gonna try to use the last version of agario-client, and use the old packets and add the encryption. Hope it works :)

**Comment by ZfsrGhS953** [comment]
No, it's double encrypted, the first key starts at 673720360 (0x40404040 hex) and changes after each reset all cells packet. The other one changes every message and I don't know the algorithm. I don't know in which order they are applied as well. So you can't just replace packets in agario-client with new.

**Comment by mbm3** [comment]
@ZfsrGhS953 I was talking about a websocket mask that applies the XOR...
