### ISSUE TITLE
i couldnt make it

### ISSUE THREAD

**Issue by diriklik** [pulviscriptor/agario-client#25]
im using camilleeyriess script. but theres an error and i dont know how to fix that. by the way sorry about my english. i hope you r understand me.

Error video; https://www.youtube.com/watch?v=ETjXVaTW0vY&feature=youtu.be

http://www.megafileupload.com/hUqP/agario-client.rar
http://www.filedropper.com/agario-client

**Comment by camilleeyries** [comment]
I'm french and my english is very bad too :)... hello ! I understand the problem... You need to place the file "agario-client.js" (obtained with npm install agario-client) with all his other file in the same folder od my script... I work on an other version of my script because other cell eat the cameraman when I connect to a server... (if you are french too, end me a mp :+1: )

**Comment by camilleeyries** [comment]
... I have create a repository for my script, https://github.com/camilleeyries/Acteur-agario-client-Aim-Bot

**Comment by camilleeyries** [comment]
https://github.com/camilleeyries/Acteur..js-agario-client-aimbot/

**Comment by pulviscriptor** [comment]
camilleeyries, you do not need to do that. You do it wrong.
diriklik, 
you do:
`node ./node-modules/agario-client/example.js`
you need:
`node ./node_modules/agario-client/example.js`
So there is "node_modules" not "node-modules"

**Comment by pulviscriptor** [comment]
camilleeyries, if you do `require('./agario-client.js');` this is wrong, you need to do `require('agario-client')` and then you do not need to copy any files anywhere.

**Comment by camilleeyries** [comment]
ok thanks :)

**Comment by pulviscriptor** [comment]
diriklik, can you confirm that your problem is solved?

**Comment by diriklik** [comment]
i dont understand programming. im playin agario on party mode. and i didnt see server,key thing in your example.js

i just saw it in camilleeyriess example.js, i wrote ws:// and party key but it didnt work. i couldnt see worker or smt.

Node said workers r connecting. i dont know where i made a mistake.

**Comment by pulviscriptor** [comment]
diriklik,
 Okay, this is not `agario-client` issue, but i looked at [script](https://github.com/camilleeyries/Acteur..js-agario-client-aimbot/blob/master/Acteur.V.2.js)
And you can try do:
```javascript
var serveur = "";
var serveurKEY = "http://agar.io/#4UR4A";
```
Replace URL to yours.
If you have more questions then please contact author of bot - [camilleeyries](https://github.com/camilleeyries)

**Comment by camilleeyries** [comment]
Hello everybody ! ActeurV2 don't work for the moment because workers can't reconize acteur... Somebody can fix this :-) ?
