### ISSUE TITLE
Developing of client will be freezed for a while

### ISSUE THREAD

**Issue by pulviscriptor** [pulviscriptor/agario-client#27]
I got some problems, doctors says i need surgery. I am going to hospital now. I will be away for about two weeks (i hope not more that month).
For that time i will not be able to fix agario client if it breaks.
Bye.

**Comment by DeepSnowNeeL** [comment]
Kind of you to let us know.
Wish you a speedy recovery.

Thanks for your good work !

Le mar. 3 nov. 2015 16:38, pulviscriptor <notifications@github.com> a
écrit :

**Comment by camilleeyries** [comment]
Good recovery :-)

**Comment by Lokke** [comment]
hope that this issue can be debuged fast.
good recovery

**Comment by nguyenvanduocit** [comment]
Thanks for your awesome client implement. really awesome.
and good health !

**Comment by AmazingGamerBoy** [comment]
Anyone willing to help me create an agario suicide/feeder bot with over 150 bots? This needs to be a local script. It would be fine to edit another script such as pulviscriptor's. Will pay a bit of money if you want (but just a bit). Add me on skype to talk about this: Agario-Lord
