### ISSUE TITLE
Agar

### ISSUE THREAD

**Issue by wahm22** [pulviscriptor/agario-client#28]
Hi

I have some problem and need some help

Please add me on skype  sir

live:Pro_Sauron

**Comment by DeepSnowNeeL** [comment]
Why don't you write what is your problems so we can help here ?

**Comment by wahm22** [comment]
I can't cuz i have alot of questions : D
Plz add me on skype @DeepSnowNeeL

**Comment by nguyenvanduocit** [comment]
That's not issue, please don't create an issue here :dancers:

**Comment by camilleeyries** [comment]
😜😎😫😸😧😇😵😬😏😆

**Comment by AmazingGamerBoy** [comment]
Anyone willing to help me create an agario suicide/feeder bot with over 150 bots? This needs to be a local script. It would be fine to edit another script such as pulviscriptor's. Will pay a bit of money if you want (but just a bit). Add me on skype to talk about this: Agario-Lord
