### ISSUE TITLE
init key has changed

### ISSUE THREAD

**Issue by henopied** [pulviscriptor/agario-client#32]
You should change the init key to `2200049715` I don't know if this has caused problems yet but it may lead to instability.

**Comment by pulviscriptor** [comment]
If somebody experience some problems because of new key, please report them here.
Currently i do not have access to my PC. I hope i will investigate what new key causes in protocol behavior and fix it in next 24 hours.

**Comment by henopied** [comment]
To fix this in the future could you just have a script that checks if there is an `indexOf` the current init key in this client and if there is not it would notify you?

**Comment by pulviscriptor** [comment]
@henopied
I may do it someday.
