### ISSUE TITLE
UInt32 "player" x and y

### ISSUE THREAD

**Issue by Sonicmaster13** [pulviscriptor/agario-client#33]
Dear pulviscriptor, 
  This is not an issue, but i don't know another way of contacting you.
I really need to know how to, in a userscript or extension for chrome, get the players X and Y value, constantly update it, and log it to localStorage.x and localStorage.y (updated every 100 ms). I know that the players X and Y values are sent through Uint32 packets (at least i think......), but i have tried many methods on extracting the packets in a userscript, but none of them work. Any help is appreciated, and if you would like another way of communicating, just let me know and i will close this 'issue' and we can use that. thanks in advance!

**Comment by pulviscriptor** [comment]
Sonicmaster13,
I am not sure, are you talking about original client or my lib.
In my lib there is events for coordinates update so i will assume you are talking about original client.
So i checked original code, and my answer is - i do not know. 
You should ask somewhere else i think.

    i don't know another way of contacting you

You can find my email in [readme](https://github.com/pulviscriptor/agario-client#feedback) and my [profile](https://github.com/pulviscriptor)
