### ISSUE TITLE
question about nickname

### ISSUE THREAD

**Issue by agarioBotDev** [pulviscriptor/agario-client#35]
hey Dude !

your script is very usefull for me, but i really tried hard to get the nickname from the other balls around
, adding sth to the appear in agario-client.js....is there a way to get the nickname of a ball, or is it anywhere stored in the packet? (i don't mean the nickname of your bots) i want them to go into sb, when appear

thanks,
David

**Comment by agarioBotDev** [comment]
or how is it possible to get the x and y coordinate of my cell in the browser ?
can't find something usefull...

**Comment by pulviscriptor** [comment]
I'm not sure i correctly understood your question. Don't know that is `adding sth to the appear` and ` i want them to go into sb` but i will try.

    nickname from the other balls around
If you want really "around" balls, lets count this like "balls on screen". 
Balls objects have `ball.visible` property, which shows is ball visible on screen, and `ball.name` which have nickname of player, if he set his nickname. 
So here is code for `examples/basic.js` that will show all nicknames around you after 5 seconds.
```javascript
setTimeout(function(){ //timer for 5 seconds
    console.log('SEARCHING FOR BALLS AROUND ME!');
    for(var ball_id in client.balls) {
        if(!client.balls.hasOwnProperty(ball_id)) continue; //prototype can get in the way

        var ball = client.balls[ball_id];
        if(!ball.visible) continue; //this ball is not on the screen
        if(!ball.name)    continue; //this ball don't have a nickname
        if(ball.mine)     continue; //this is our ball

        console.log('I see ball with nickname near me! ID ' + ball_id + ' and nickname ' + ball.name);
    }
}, 5000);
```
![example](https://i.imgur.com/PAIpS9Q.png)
You can find full list of properties in [readme](https://github.com/pulviscriptor/agario-client#ball-properties)

    how is it possible to get the x and y coordinate of my cell in the browser
Can't help with that. I code my own lib without using original code from browser. I don't know where and what stored there.

**Comment by agarioBotDev** [comment]
@pulviscriptor that's exactly what i want, but don't know why it doesn't work for me (picture above)...and how can i add this to multiple ?
![error](https://cloud.githubusercontent.com/assets/16101422/11506707/030e6c98-9851-11e5-8b6b-756a71da2556.png)

**Comment by pulviscriptor** [comment]
Also here is code for `ballAppear` event
```javascript
client.on('ballAppear', function(ball_id) {
    var ball = client.balls[ball_id];
    if(ball.name) console.log('NEW BALL WITH NICKNAME APPEARED! ID ' + ball_id + ', nickname ' + ball.name);
});
```
agarioBotDev, i pasted code to end of the file `basic.js`. Maybe you pasting it in wrong place. Show me your `basic.js` where you pasted code.

> how can i add this to multiple

Its up to you, i don't know where you want it.

**Comment by agarioBotDev** [comment]
ok the timer works now, the ballAppear event not, don't know why...
i added this to the multiple.js:
```
bot.client.on('ballAppear', function (ball_id) {
            var ball = client.balls[ball_id];
            if (ball.name == "somone") console.log('NEW BALL WITH NICKNAME APPEARED! ID ' + ball_id + ', nickname ' + ball.name);
        });
```

what i'm doing wrong ?

PS: thanks for your great help :+1:

**Comment by pulviscriptor** [comment]
Try to replace 
`var ball = client.balls[ball_id];`
with
`var ball = bot.client.balls[ball_id];`

**Comment by agarioBotDev** [comment]
thanks, works

**Comment by agarioBotDev** [comment]
one last question...
do you have an idea why this doesn't work ?

```javascript
bot.client.on('ballAppear', function (ball_id) {
            var ball = bot.client.balls[ball_id];
            if (ball.name == "[Dm] Master")
            {
                console.log('Master appeared !');
                bot.interval_id = setInterval(function () { bot.recalculateTarget() }, 1000000000); // to give the bot enough time to move to me --> next line
                bot.client.moveTo(ball.x, ball.y);                                                  // here the bot have to move to me, but it doens't work, he still search for this little pieces...?
            }

        });
```

**Comment by pulviscriptor** [comment]
I don't know what is wrong there, but i see what you trying to do.
You can choose easier way to do this. 
You can just modify `recalculateTarget()` and add just one line to it
```javascript
            var ball = bot.client.balls[ball_id];
            if(ball.virus) continue;
            if(!ball.visible) continue;
            if(ball.mine) continue;
            if(ball.name == 'yourname') return bot.client.moveTo(ball.x, ball.y); //add this line here
            if(ball.size/my_ball.size > 0.5) continue;
```
Didn't tested, but should work.
