### ISSUE TITLE
Is there a way to get more than 5 clients on the same server

### ISSUE THREAD

**Issue by DaAwesomeRazor** [pulviscriptor/agario-client#44]
Is it possible to get more than 5 clients to be on the same server? I have tried vanessa socket pipe, and socks 5. They both didn't work. I have access to a vps and multiple ips are on the adapter. I was researching about some localAddress thing. Is there some alternative way to get more than 5 clients connected to the same server.

ALSO IMPORTANT: if you change the token to null it works on ffa,experimental,and teams :D

**Comment by pulviscriptor** [comment]
>if you change the token to null it works on ffa,experimental,and teams

Previously if you join with same `facebook_key` (now its `auth_token`) server would kill all other connections with this key.
So i can't say how tokens works now.
If you can't join more than 5 clients using SOCKS (without auth_token) this is an issue. But if you using token from same account for all connections, i don't know what will happen.

**Comment by DaAwesomeRazor** [comment]
I may have not been using SOCKS correctly though. I am also getting this annoying error when i try to run the new auth_token.js that you added in the examples.

HTTP code: 302
Redirect: https://www.facebook.com/login.php?skip_api_login=1&api_key=677505792353827&signed_next=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.3%2Fdialog%2Foauth%3Fredirect_uri%3Dhttps%253A%252F%252Fagar.io%26scope%3Dpublic_profile%252C%2Bemail%26response_type%3Dtoken%26client_id%3D677505792353827%26ret%3Dlogin&cancel_url=https%3A%2F%2Fagar.io%2F%3Ferror%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%23_%3D_&display=page

**Comment by DaAwesomeRazor** [comment]
Did I do something wrong


node socks.js 5 localhost 8080
Example will use SOCKS server localhost:8080 version 5
Failed to request server (error=REQUEST_ERROR, error_source=Error: Socket Closed)

**Comment by pulviscriptor** [comment]
Are you sure localhost:8080 is working SOCKS version 5 server?
Test it with some software, like web browser. Google how to set SOCKS server in your web browser and check if websites opens.
It must be non-working SOCKS server. If it will work in browser, but not in example, this will be slow and hard to debug it for non-experienced user.

**Comment by DaAwesomeRazor** [comment]
I dont think it was a working socks5 server. How can I host one?  

PS: Thanks for taking your time to answer these questions. I am really stupid at times and dont really understand these types of stuff

**Comment by pulviscriptor** [comment]
>How can I host one

For testing i used [ssspl](http://ssspl.sourceforge.net/)
Please do not allow anybody from internet connect to your SOCKS port.

**Comment by Agarian** [comment]
ITS SUPER EASY GET BROWSEC FOR CHROME:
https://chrome.google.com/webstore/detail/browsec/omghfjlpggmjjaagoclmmobgdodcjboh?hl=en
