### ISSUE TITLE
Auth token broken

### ISSUE THREAD

**Issue by DaAwesomeRazor** [pulviscriptor/agario-client#45]
I am getting this annoying error when i try to run the new auth_token.js that you added in the examples.

HTTP code: 302
Redirect: https://www.facebook.com/login.php?skip_api_login=1&api_key=677505792353827&signed_next=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.3%2Fdialog%2Foauth%3Fredirect_uri%3Dhttps%253A%252F%252Fagar.io%26scope%3Dpublic_profile%252C%2Bemail%26response_type%3Dtoken%26client_id%3D677505792353827%26ret%3Dlogin&cancel_url=https%3A%2F%2Fagar.io%2F%3Ferror%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%23_%3D_&display=page

**Comment by pulviscriptor** [comment]
"https://www.facebook.com/login.php" most likely means you set wrong c_user,datr,xs cookies.
You must login on http://agar.io through facebook and then copy c_user,datr,xs cookies from http://facebook.com/
Also your cookies must be URL decoded (not `a%3Ab%3Ac` but `a:b:c`)
Or you can try go to that redirect URL, login there and then copy cookies from http://facebook.com again.
Something of that should help.

**Comment by DaAwesomeRazor** [comment]
How can I do that? Here are my steps:
I go to agar.io.
inspect element
resources
cookies
then www.facebook.com and copy all the stuff
how do I decode it

**Comment by pulviscriptor** [comment]
Google "url decode" gave [this](http://meyerweb.com/eric/tools/dencoder/)

**Comment by DaAwesomeRazor** [comment]
Thank You, It worked!!
