### ISSUE TITLE
How to run this client in browser?

### ISSUE THREAD

**Issue by lulzyyy** [pulviscriptor/agario-client#48]
It looks awesome but I have no idea how to run it... please help me

**Comment by pulviscriptor** [comment]
@lulzyyy
I have a question since i receive lots of emails from peoples thinking this is a bot. 
Do you think "agario-client" is a bot for agar.io? If you do, it is not. It is library for making your own clients/bots. But you need to know JavaScript to do that.

In case you asking correct thing, you can use [browserify](http://browserify.org/)
Check how [agario-webclient](https://github.com/pulviscriptor/agario-webclient) uses it to make web browser agar.io client based on `agario-client` library.

**Comment by lulzyyy** [comment]
I know it's not a bot:) I have 2 modded servers in Ogar and I want to test some other clients with those servers. Using Ogar is simple- just install node.js or JxCore and execute it with 1 command. But your client seems to be more difficult to run... Anyway, can I test it on Windows?

**Comment by pulviscriptor** [comment]
@lulzyyy 
I don't think this library is what you searching for, but yes, you can run it on windows.
You need Node.js and you can check [instructions](https://github.com/pulviscriptor/agario-client#instructions)
`./node_modules/agario-client/examples/basic.js` will search and connect to agar.io server, but you can modify source code to connect it to your server.
You can replace bottom block
```javascript
AgarioClient.servers.getFFAServer({region: region}, function(srv) { //requesting FFA server
    if(!srv.server) return console.log('Failed to request server (error=' + srv.error + ', error_source=' + srv.error_source + ')');
    console.log('Connecting to ' + srv.server + ' with key ' + srv.key);
    client.connect('ws://' + srv.server, srv.key); //do not forget to add ws://
});
```
with
```javascript
client.connect('ws://1.2.3.4', '');
```
But i do not know if my client is working with ogar. Never tested it on ogar.

**Comment by lulzyyy** [comment]
It connects and spawn but then:
worker: [warning] spawn() interval gave up! Disconnecting from server!
worker: disconnect() called
worker: disconnected
worker: I lost my friend: 277(agario-client)

**Comment by pulviscriptor** [comment]
@lulzyyy 
I assume that means `agario-client` is not supporting ogar.

**Comment by lulzyyy** [comment]
It's sad because Ogar is actually the most popular... Do you know any custom client for ogar?

**Comment by pulviscriptor** [comment]
@lulzyyy 
I do not know, but i think you search/ask in Ogar project https://github.com/OgarProject/Ogar

**Comment by lulzyyy** [comment]
OK thanks... Anyway, are there custom servers like Ogar that your client supports?

**Comment by pulviscriptor** [comment]
@lulzyyy 
Theoretically yes. Theoretically maybe older versions of `agario-client` supports Ogar. 
You can do `npm view agario-client versions` and then install any version like `npm install agario-client@0.0.5`
But i recommend not to use `agario-client` with Ogar, it was not made for it.

**Comment by markelite** [comment]
@lulzyyy How did you manage manage to make it work on Ogar-Unlimited?

**Comment by lulzyyy** [comment]
just download Cigar client. In ogar unlimited you need to change offsets in updateNodes.js to make client communicate with Ogar properly

**Comment by markelite** [comment]
@lulzyyy so I just need the `client` folder from Cigar? I'm looking at the two `UpdateNodes.js` and I really don't understand it. :/

**Comment by lulzyyy** [comment]
Yes you need client folder "client" and Ogar Unlimited. In Ogar Unlimited, you must change offset values in updateNodes.js to same values as in Cigar's version of updateNodes.js.

**Comment by markelite** [comment]
But Ogar-Unlimited seems to have more parameters and objects than Cigar's `UpdateNodes.js`'s has.

Ogar-Unlimited have this as UpdateNodes function:
```
function UpdateNodes(destroyQueue, nodes, nonVisibleNodes, scrambleX, scrambleY) {
  this.destroyQueue = destroyQueue;
  this.nodes = nodes;
  this.nonVisibleNodes = nonVisibleNodes;
  this.scrambleX = scrambleX;
  this.scrambleY = scrambleY;
}
```

Cigar:

```
function UpdateNodes(destroyQueue, nodes, nonVisibleNodes) {
    this.destroyQueue = destroyQueue;
    this.nodes = nodes;
    this.nonVisibleNodes = nonVisibleNodes;
}
```

Ogar Unlimited:
```
    view.setUint32(offset, node.nodeId, true); // Node ID
    view.setInt32(offset + 4, node.position.x + this.scrambleX, true); // X position
    view.setInt32(offset + 8, node.position.y + this.scrambleY, true); // Y position
    view.setUint16(offset + 12, node.getSize(), true); // Mass formula: Radius (size) = (mass * mass) / 100
    view.setUint8(offset + 14, node.color.r); // Color (R)
    view.setUint8(offset + 15, node.color.g); // Color (G)
    view.setUint8(offset + 16, node.color.b); // Color (B)
    /////view.setUint8(offset + 17, node.spiked, true); // Flags
    /////
    view.setUint8(offset + 17, (node.spiked | 4)); // Flags
    /////
    offset += 18;
```
Cigar:
```
        view.setUint32(offset, node.nodeId, true); // Node ID
        view.setUint16(offset + 4, node.position.x, true); // X position
        view.setUint16(offset + 6, node.position.y, true); // Y position
        view.setUint16(offset + 8, node.getSize(), true); // Mass formula: Radius (size) = (mass * mass) / 100
        view.setUint8(offset + 10, node.color.r, true); // Color (R)
        view.setUint8(offset + 11, node.color.g, true); // Color (G)
        view.setUint8(offset + 12, node.color.b, true); // Color (B)
        view.setUint8(offset + 13, node.spiked, true); // Flags
        offset += 14;
```

and Cigar had this commented out:
```
    var skin = node.getPremium();
    if (skin) {
      for (var j = 0; j < skin.length; j++) {
        var c = skin.charCodeAt(j);
        if (c) {
          view.setUint8(offset, c);
        }
        offset++;
      }
    }
    view.setUint8(offset, 0); // End of string
    offset++;
```


It would've probably been easier if it was the other way around. :smile:
