### ISSUE TITLE
i have no idea what to do with this

### ISSUE THREAD

**Issue by Agarian** [pulviscriptor/agario-client#49]
its a bit too complicated for me :/

**Comment by AgarioCheats** [comment]
Hey Agarian! So basically this is a client, but WITHOUT A BROWSER. So before, you used to enter "http://agar.io" to play. What this does, is that it connects to agar.io and plays as a bot (as the source code is written at basic.js) just running through node. So you can't actually see or control the bot, you only see it if you enter on your browser to the server it is connected to.
What can you do with this?
Well you can recode it using the API.

**Comment by pulviscriptor** [comment]
@Agarian 
This is not a bot. This is not a cheat. This is not for playing agar.
This is library (set of functions) for developers/programmers/coders written on [JavaScript](//google.com?q=javascript) language to speak with agar using its protocol.
If you do know JavaScript you can get all information that you need in [readme](https://github.com/pulviscriptor/agario-client/blob/master/README.md) file.
If you will have issues with library feel free to create new issue.

**Comment by pulviscriptor** [comment]
@AgarioCheats 
>you only see it if you enter on your browser to the server it is connected to, you will see it playing

Actually you can watch client playing in browser in real time and even recording his games and then watch them over and over again in browser using [agario-devtools](https://github.com/pulviscriptor/agario-devtools)

**Comment by Agarian** [comment]
that's the complicated part. will you answer my question or no because someone should make a video on this

**Comment by pulviscriptor** [comment]
@Agarian
Sure, here is some videos for you
https://www.youtube.com/results?search_query=leaing+javascript
https://www.youtube.com/results?search_query=leaing+node.js
