### ISSUE TITLE
Client is broken due to protocol change

### ISSUE THREAD

**Issue by pulviscriptor** [pulviscriptor/agario-client#5]
Working on it.
Just you to know.

**Comment by pulviscriptor** [comment]
Fixed.

**Comment by pulviscriptor** [comment]
Still don't understand how to use this.

**Comment by GeoffreyFrogeye** [comment]
@pulviscriptor https://help.github.com/articles/closing-issues-via-commit-messages/
"Fixes #5" would do :wink:
