### ISSUE TITLE
How do you have make this script...

### ISSUE THREAD

**Issue by camilleeyries** [pulviscriptor/agario-client#51]
Hello ! I want to make an userscript for cursors.io but I don't know how capture, decrypt and repeat websocket traffic...
Can you help me ?

Thanks *:D*

**Comment by davidmann4** [comment]
Actually this is a nodejs client which allows you to write headless clients. So you run them inside a terminal. Since there is an open source server for the game the author most probably took a look at the source of it: https://github.com/OgarProject/Ogar 

But I guess at some point a developer had to reverse engineer the protocol.

Did you tried wireshark? http://stackoverflow.com/questions/12650083/how-to-debug-websockets-with-wireshark

**Comment by pulviscriptor** [comment]
@camilleeyries
Hi.
You need to find what is main file of game that you need.
Then paste code of that js file in http://jsbeautifier.org/ and then look what it do.
There is also upgraded version of deobfuscator http://www.jsnice.org/ but do not replace name of variables, or you will not understand where is names left by obfuscator and where is names created by deobfuscator.
Then block original file and replace it with your new one to able to add `console.log`, `alert` and `console.trace` (<b>this one is awesome for reverse engineering</b>) and see what happens.
To replace i use complicated proxy-involved way replacing content of files transparently to site scripts and browsers, but i think you can use greasemonkey or something like that for your needs. 

<sub>Today repo like exploded, so much new issues, so much comments.
Need to sleep. Good night.</sub>

**Comment by davidmann4** [comment]
which proxy did you used? mitmproxy? 

https://github.com/mitmproxy/mitmproxy

**Comment by pulviscriptor** [comment]
@davidmann4
I use squid with redirectors http://wiki.squid-cache.org/Features/Redirectors (check manual for your squid version, they changed redirector format answer few times) and local webserver to serve content for files that i want to replace. Also i have there fake CA to generate certificates to work with SSL too. So you can replace files in any browsers and any applications. Very useful. 
And you can forward all your traffic to machine with `squid` (by replacing `default gateway`) and using `iptables` route HTTP traffic (not sure about SSL) to `squid` absolutely transparently for OS. So software will know nothing about it getting MitM'ed.
Google something like `iptables squid transparent`.

Now i really need to go.

**Comment by DeltaEnemy** [comment]
@pulviscriptor This can be used to connect more than 5 bots?

**Comment by pulviscriptor** [comment]
@DeltaEnemy
Yes it can be. Check `socks.js` in examples folder.

**Comment by davidmann4** [comment]
@pulviscriptor do oyu have expirence using +5 bots? do you need to onboard them over a longer time span or can I just connect them all at once?

**Comment by pulviscriptor** [comment]
@davidmann4
I did not used more than 5 bots from example. Can't say.

**Comment by DaAwesomeRazor** [comment]
@davidmann4  https://www.youtube.com/watch?v=NYIhwC-bVY4 
thats what happens when you use 132 mass bots..
Btw those are my bots :D

**Comment by davidmann4** [comment]
cool - I made a repo for feed-bots based on this framework: 
https://github.com/davidmann4/agario-feeder-bot
