### ISSUE TITLE
Im a noob how do i make this run?

### ISSUE THREAD

**Issue by BLUclanTDS** [pulviscriptor/agario-client#52]
I want to use this so my bots from agarpowerups will have face book mass. I put my access token in agario-client.js and put my facebook cookie info in auth_token.js When i go on to agar.io and run my bots it dosnt work. Any help??

**Comment by Agarian** [comment]
same

**Comment by pulviscriptor** [comment]
Read all this page https://github.com/pulviscriptor/agario-client 
There is all info you need.

**Comment by BLUclanTDS** [comment]
How do I check the console to see if there's errors

**Comment by pulviscriptor** [comment]
@BLUclanTDS
There would be error message and script will stop running.

**Comment by BLUclanTDS** [comment]
What scrip where's the error message??

**Comment by pulviscriptor** [comment]
@BLUclanTDS
This project made for developers. I assume you are not one of them and you do now know JavaScript language.
If you want to learn JavaScript you can google some basics for beginners and look if you like it and learn it.

**Comment by BLUclanTDS** [comment]
My friend made a modification for his agar.io bots. He told me how to do it and set it up but since he is studying for finals he hasn't been able to tell me how to run it or see if there's a error.

**Comment by BLUclanTDS** [comment]
Do I just download the developer thing you have in the read me

**Comment by pulviscriptor** [comment]
>Do I just download the developer thing

Its little more complicated than this. 
Lets try this: https://www.codecademy.com/learn/javascript
Go there and look if you like it. See if you like JavaScript language and programming at all.
