### ISSUE TITLE
5 connections Limit

### ISSUE THREAD

**Issue by davidmann4** [pulviscriptor/agario-client#53]
Hey, just opened 8 tabs and played on the same server - why does your framework only allow 5 simultanious connections?

**Comment by camilleeyries** [comment]
Use proxy...

**Comment by davidmann4** [comment]
there seems to be a technical problem - we should be able to use the real limit and not get limited by the framework.

**Comment by pulviscriptor** [comment]
@davidmann4
There is no limit by `agario-client` if you mean that. agar.io server refusing connections from IP when there is 5 connections established from IP already.

**Comment by davidmann4** [comment]
But I can establish 8 connections with my browser.

**Comment by pulviscriptor** [comment]
@davidmann4
Tested in browser. Connected to one party from 7 tabs. 
First 5 are connected to party.
2 other connected to some random servers with completely different players on it.
I think you got "fooled" by this "illusion". I almost got too, but check nicknames in top10 players box.

**Comment by davidmann4** [comment]
ahh ok will check - pretty tricky :)

**Comment by davidmann4** [comment]
confirmed /close
