### ISSUE TITLE
Make Header Value customizable

### ISSUE THREAD

**Issue by davidmann4** [pulviscriptor/agario-client#54]
Hey,

I would like to add Header informations here: (user-agent)

https://github.com/pulviscriptor/agario-client/blob/master/agario-client.js#L41

can you provide an optinal parameter ? should I make a pull request?

cheers,
David

**Comment by pulviscriptor** [comment]
Now you can do
```javascript
var client = new AgarioClient('worker_1');
client.headers['user-agent'] = 'My user agent';
client.connect(...);
```

**Comment by davidmann4** [comment]
ahh cool thx!
