### ISSUE TITLE
IP Binding?

### ISSUE THREAD

**Issue by TheMaskedMonkey** [pulviscriptor/agario-client#55]
Is there a way to bind the use of a separate ip on a server? I have multiple ips and don't really want to use the server's main ip when using this! It would also be a nice feature all together anyways

Thanks!

**Comment by pulviscriptor** [comment]
@TheMaskedMonkey
Commited https://github.com/pulviscriptor/agario-client/commit/29391b12d05bbb4d921cdff2bf30551eff67b9a7
But i do not have server with multiple interfaces. Can you please test and report if it works?
You need to replace files `agario-client.js` and `servers.js` in `node_modules/agario-client` path with new ones.
https://raw.githubusercontent.com/pulviscriptor/agario-client/master/agario-client.js
https://raw.githubusercontent.com/pulviscriptor/agario-client/master/servers.js
Usage is
```javascript
client.local_address = '1.2.3.4';
```
and
```javascript
AgarioClient.servers.getpartyServer({party_key: 'PARTY_KEY_KERE', local_address: '1.2.3.4'}, function(srv) { 
    if(!srv.server) return console.log('Failed to request server (error=' + srv.error + ', error_source=' + srv.error_source + ')');
    console.log('Connecting to ' + srv.server + ' with key ' + srv.key);
    client.connect('ws://' + srv.server, srv.key); //do not forget to add ws://
});
```

**Comment by TheMaskedMonkey** [comment]
Wow yes it worked! Thank you kind sir! :)

**Comment by pulviscriptor** [comment]
Updated lib in npm.
You can do `npm update`

**Comment by TheMaskedMonkey** [comment]
So I just looked further in to it and it isn't binding properly. All the bots are from the main ip still http://i.imgur.com/j4X5WSm.png

**Comment by TheMaskedMonkey** [comment]
Looking in to it further with a friend, we found it didn't actually do anything. Here:

https://i.imgur.com/j4X5WSm.png

**Comment by TheMaskedMonkey** [comment]
We resolved this by updating to the latest websocket! You might want to note that somewhere :)

**Comment by DaAwesomeRazor** [comment]
Use LocalAdress

**Comment by camilleeyries** [comment]
Wait a second... ip binding can bypass agario ip protection ?

**Comment by pulviscriptor** [comment]
@TheMaskedMonkey
Updated package.json to ws ^1.0.1, now `npm update` will install 1.0.1
@camilleeyries
If your have more than 1 interface/IP on interface, you can choose from what IP/interface send requests.

**Comment by TheMaskedMonkey** [comment]
@camilleeyries Of course, as @pulviscriptor said, if you have more than 1 ip assigned to your system you can use them giving you 5 extra bots to play with. Agario's protection only blocks more than 5 connections per ip so use more ips and well, you win ;)

**Comment by camilleeyries** [comment]
... How can I obtain multiple ip ? Im on mac Yosemite...

**Comment by TheMaskedMonkey** [comment]
You don't just get ips. You need to buy them and 90% of the time you can't get more than one IP on a home connection unless you're on a business plan. I have multiple servers with like 5 IPv4's each so that's why I'm using it :>

**Comment by camilleeyries** [comment]
It's interesting :D... i have a server but I don't know how many ip I have

**Comment by TheMaskedMonkey** [comment]
It all depends how many you pay for. It'll be on your control panel for the server :3

**Comment by DaAwesomeRazor** [comment]
Use socks5 mann. https://www.socks-proxy.net/
