### ISSUE TITLE
Advanced AI bot

### ISSUE THREAD

**Issue by TheMaskedMonkey** [pulviscriptor/agario-client#57]
So this is more of a question for people rather than issue but is there any nice clean examples of an advanced AI written for this? I can't seem to find many examples except for the 4 included. Thanks! :)

**Comment by DaAwesomeRazor** [comment]
I am thinking of starting to make one

**Comment by TheMaskedMonkey** [comment]
My friend is also considering making one. This is an amazing API which in my opinion needs a lot more light within the Agario community! :)

**Comment by matheusportela** [comment]
I was planning to develop an AI agent using Reinforcement Learning (such as Q-learning) for agar.io and I came across this API. I would be interested in joining such an effort.

**Comment by TheMaskedMonkey** [comment]
I'd happily contribute if somebody made a repo for this ;>

**Comment by TheMaskedMonkey** [comment]
Any update on whether somebody is down for this?

**Comment by pulviscriptor** [comment]
@TheMaskedMonkey 
https://github.com/davidmann4/agario-feeder-bot

**Comment by TheMaskedMonkey** [comment]
Thanks! Going to give it a try! :>
