### ISSUE TITLE
Connecting more than 5 Bots

### ISSUE THREAD

**Issue by thisismo** [pulviscriptor/agario-client#58]
If I'm trying to connect more than 5 bots with socks, the first 5 are connecting fine but the next bots are displaying this error:
Failed to request server (error=REQUEST_ERROR, error_source=Error: Negotiation Error (5))
Failed to request server (error=REQUEST_ERROR, error_source=Error: Socket Closed)

**Comment by pulviscriptor** [comment]
@thisismo
Make sure you don't use more than 5 connections through one SOCKS. Looks like it.

**Comment by thisismo** [comment]
Would you like to take a look on my code?

**Comment by pulviscriptor** [comment]
You can email me it pulviscriptor@gmail.com i will look what is there.

**Comment by thisismo** [comment]
Done :)
