### ISSUE TITLE
Bots not spawning in

### ISSUE THREAD

**Issue by DaAwesomeRazor** [pulviscriptor/agario-client#65]
All of sudden my script keeps saying. Connected! then right when it connects it disconnects them. Its probably because of the new update. I made it so now it connects 3 clients per proxy now. Also facebook is broken, but you are probably aware of that

**Comment by DaAwesomeRazor** [comment]
I found one of my old scripts that used to work. http://pastebin.com/1S8LEtAb

**Comment by pulviscriptor** [comment]
Tested `examples/basic.js` for hour, works fine.
Tested `examples/auth_token.js` - generates valid tokens.
Tested `examples/basic.js` with token, spawning bigger mass than without key.
So `agario-client` is fine, don't see any problems there.

**Comment by thegreat1200** [comment]
@pulviscriptor If he is saying what I think he his saying, I'm having the same problem, I connect to Agar.IO on a browser and I can't connect my bot

**Comment by DaAwesomeRazor** [comment]
@pulviscriptor  I am sooo stupid. Just fixed my script

**Comment by pulviscriptor** [comment]
@thegreat1200
Do examples works for you?

**Comment by thegreat1200** [comment]
http://grantsommer.com/pictures/error.png

**Comment by pulviscriptor** [comment]
@thegreat1200
Are you trying to connect to one IP using key from another? You can't do that.
You need to use IP and key received from `servers.getFFAServer`

**Comment by thegreat1200** [comment]
@pulviscriptor How would I get the key from an IP?

**Comment by pulviscriptor** [comment]
@thegreat1200
You <s>can't</s> need to request FFA servers from region until you get that same IP and then connect there and check if there are same leaders as on the server that you searching for.
But if you will do that too fast, you will get banned.
Also key must be requested from same IP that you will be connecting from.

**Comment by issy123** [comment]
@pulviscriptor

I don't want to disrespect you, you made an awesome script but the solution you are telling him is verry inconvenient.

@thegreat1200

If you requested an ffa server from you nodejs script you can get the key from the functiom argument with serv.key as seen on https://github.com/pulviscriptor/agario-client/blob/master/examples/basic.js

But if you did manage to get an ip from agar.io with your browser as far as i know its difficult to get the key.

But if it is an party the key is the party hashtag without '#'

**Comment by pulviscriptor** [comment]
@issy123
My experiments shows that you can not use one key twice. 
You can replace `createPartyServer` to `getFFAServer` in [line 141](https://github.com/pulviscriptor/agario-client/blob/master/examples/multiple.js#L141)
And only one bot will be able to connect. 
But if you are able to connect to FFA server multiple times using one key, i think you found some bug in agar.
