### ISSUE TITLE
How can I detect when an ejected mass is eaten?

### ISSUE THREAD

**Issue by thegreat1200** [pulviscriptor/agario-client#67]
How can I detect when another player's ejected mass is eaten by the bot

**Comment by pulviscriptor** [comment]
In agar.io protocol ejected mass is not marked as some special ball. Its just little ball. You even can't know if it is player or not.
But if we assume that such little players are not possible in agar and moving food is not possible too then you can do logic like "if little ball moving, then it is ejected mass", "if it moving away from me and have same color, it is ejected from me", and add "ball.my_ejected_mass = true;" and check it when ball gets eaten.
*I do not know if this is good way to do it or not, but this is what i would do if i would need that.*

**Comment by issy123** [comment]
All ejected mass has the same algorithm. When you eject mass it will be thrown for example 250 distance away from the player in an random direction. After that the ejected mass does not move and will always be an certain mass. So like pulviscriptor said. You can easily seperate an ejected mass from an player. It has certain properties and algorithms
