### ISSUE TITLE
Facebook Bots

### ISSUE THREAD

**Issue by thisismo** [pulviscriptor/agario-client#68]
My Auth-Token is getting created successfully and im setting it to the client but ingame my bots aren't logged in.

**Comment by thisismo** [comment]
I think it's the because of the new agario patch.

**Comment by thisismo** [comment]
Ok, since the new Patch you can only have 1 IP connected with the same Facebook Account in a Party.

**Comment by issy123** [comment]
How can we get more facebook logged in bots on the same party?

Do we really need to create an list of facebook accounts???

**Comment by thisismo** [comment]
Unfortunately, yes.

**Comment by issy123** [comment]
For those who want facebook logged in bots need to collect allot facebook accounts from friends with lvl 34+ or buy 100 facebook accounts from an service and wait till they are lvl 34, will cost maybe 3 days gameplay as bot
