### ISSUE TITLE
Merged balls are not removed from memory

### ISSUE THREAD

**Issue by pulviscriptor** [pulviscriptor/agario-client#7]
I was testing `example.js` and found that when you eat your own ball, it's not removed from array and not destroyed, so when all your balls eaten, you stuck.
Merge was removed [here](https://github.com/pulviscriptor/agario-client/commit/e51e6856f42fc34cb0751f1176ebb9c0fb675061#diff-70581ff48eeec811b2c54cc41763e4c2L263) and I need time to investigate how it works in new protocol.
If you have/had this bug, this is it.

**Comment by pulviscriptor** [comment]
That was kinda lame to forgot to fix merging 12 days ago.
Who knows what also I could forgot to test/fix. Oh wait, I know. [This](https://github.com/pulviscriptor/agario-devtools/commit/dd4c4c9f45cfb6b577ac91928ba61c5d86e30d77).

**Comment by paakshik** [comment]
Hey
