### ISSUE TITLE
github tampermonkey

### ISSUE THREAD

**Issue by agarioBotDev** [pulviscriptor/agario-client#70]
i'm sorry, this is not about your project...but don't know who else i could ask.
what do i have to do that tampermonkey opens when someone click on RAW ? (in my own project)

greets,
David

**Comment by pulviscriptor** [comment]
@agarioBotDev
If i understood you correctly, you need to add some of this to head of your script
https://tampermonkey.net/documentation.php?ext=dhdg
And maybe add `.user.js` to name of file.

**Comment by agarioBotDev** [comment]
thanks
