### ISSUE TITLE
uknown packet ID(103): 67

### ISSUE THREAD

**Issue by issy123** [pulviscriptor/agario-client#71]
I am using the client for the first time and I am trying to get facebook login working.

I am getting an token but when the bot plays I get this error:

Code:
http://pastebin.com/0AyuX3qS

And by the way does the account.xs code look something like this:
220%3A0HHwXhgVLXXXXXXXXXX453651913%3A16723

The code is working correctly without facebook login

**Comment by issy123** [comment]
I found out that this packet is send when more than 1 player is using the same facebook account on the same party

**Comment by thisismo** [comment]
since the new agario update you can only connect 1 bot/player to a facebook account
