### ISSUE TITLE
???? NEED HELP

### ISSUE THREAD

**Issue by jollesnaas** [pulviscriptor/agario-client#75]
Sorry but.. how to set this up with a cigar server (or ogar)

**Comment by pulviscriptor** [comment]
`client.connect('ws://ip:port','')`
But client made only for agar.io. Working with Ogar is not guaranteed, but you can try.

**Comment by jollesnaas** [comment]
Can you help me by skype or something?

**Comment by pulviscriptor** [comment]
Sorry i can't, i'm little busy with other work i have.
But chances that this will work is low. 
https://github.com/pulviscriptor/agario-client/issues/48

**Comment by DaAwesomeRazor** [comment]
@pulviscriptor @jollesnaas  I have tried this with ogar. I have not found any bugs so far. In basic.js or mutliple.js replace `AgarioClient.servers.createParty({region: 'EU-London'}, function(srv) {
    if(!srv.server) return console.log('Failed to request server (error=' + srv.error + ', error_source=' + srv.error_source + ')');
    console.log('Engaging bots to party http://agar.io/#' + srv.key + ' on IP ' + srv.server);

    for(var bot_id in bots) {
        bots[bot_id] = new ExampleBot(bot_id);
        bots[bot_id].connect('ws://' + srv.server, srv.key);
    }
});


With   for(var bot_id in bots) {
        bots[bot_id] = new ExampleBot(bot_id);
        bots[bot_id].connect("ws://yourogarip:yourogarport");
    }
