### ISSUE TITLE
Some help please!

### ISSUE THREAD

**Issue by jollesnaas** [pulviscriptor/agario-client#76]
Hey, I have running 5 ogar server on a VPS can somone help me with setting this project up with the ogar server (or if needed cigar server)? If you can help me with setting this up I will give you creddits!
Just answer under this issue and I will read it!
Thanks!

**Comment by jollesnaas** [comment]
#75 Sorry for dupple copy...

**Comment by DaAwesomeRazor** [comment]
@jollesnaas Setting this up with an ogar server?? DO you want to connect a client to an ogar server?

**Comment by jollesnaas** [comment]
@DaAwesomeRazor Yeah something like that!

**Comment by DaAwesomeRazor** [comment]
@jashman Can you full explain. Then i may be able to help

**Comment by jollesnaas** [comment]
@DaAwesomeRazor Can you help over mail? [130948@regiuscollege.nl](mailto:130948@regiuscollege.nl)

**Comment by DaAwesomeRazor** [comment]
@jollesnaas  how about skype? My skype is santa.gaming

**Comment by jollesnaas** [comment]
I invited you but there are more than one accounts. I invited 2. If I haven't invite you please add me: jolle.snaas1

**Comment by DaAwesomeRazor** [comment]
@jollesnaas You can close this now

**Comment by issy123** [comment]
Just a little warning for u guys, don't leave your skype in public if you don't want unexpected friend requests from strangers

**Comment by jollesnaas** [comment]
@issy123 Yea, but otherwise we can't contact, I removed my skype and mail now, btw I don't use skype a lot..
