### ISSUE TITLE
How could I capture the packets being sent in agario

### ISSUE THREAD

**Issue by DaAwesomeRazor** [pulviscriptor/agario-client#77]
In agario packets are being sent and received from the server to client.

Mabye if I can replicate the opcode being sent to the server when a mass boost is bot, I can get free mass boosts. I have no way of capturing the packet though

**Comment by issy123** [comment]
In chrome developer tools in Networking -> WS filter you can see packages being send and received through an WS connection. But unfortunately it is secured so its a bit difficult to capture the right packet.

I do think they are smart enough to have server-side checking. To check if you actually have bought mass boost before you gain much mass.

But I could be wrong. I could try to search that out

**Comment by DaAwesomeRazor** [comment]
@issy123 A lot of people have claimed to hack it so I assume they are dumb to not add server side checking. it is MoneyClip..

**Comment by issy123** [comment]
@DaAwesomeRazor True that lol

**Comment by MasonBurdette** [comment]
If you figure out how to replicate the packets being sent to agar.io, tell me how to (privately).
