### ISSUE TITLE
Account Functions

### ISSUE THREAD

**Issue by DoskJS** [pulviscriptor/agario-client#78]
This is a suggestion.

Add these features to agario-client
- buy mass boost
- buy xp boost
- change skin
- check level
- check coins

EDIT (2/3/16)
also changing skin would be nice too.

This would help many people, including me, to make better bots (some w/ fb).

**Comment by thisismo** [comment]
you can check your lvl already

**Comment by MasonBurdette** [comment]
@thisismo I just noticed that xD. But having some more account functions, like the ones I suggested, would be awesome.

**Comment by pulviscriptor** [comment]
Shop is made on its own WS server `wss://web-live-v3-0.agario.miniclippt.com/ws` with its own protocol.
I don't think i will make support of it.
But i have some code for it, so if somebody want to implement it, here what may help https://github.com/pulviscriptor/agario-client/blob/master/account.js#L111

**Comment by MasonBurdette** [comment]
@pulviscriptor  ok, ill look into it.  i might contribute if i figure anything out.

**Comment by pulviscriptor** [comment]
@MasonBurdette
You can make your own repo/NPM package and i will add it as dependency. That would be better than adding another server management in client's code.

**Comment by issy123** [comment]
I found out that the event "experienceUpdate" is never emitted.

If I only could get the experience points I could calculate the level myself

**Comment by thisismo** [comment]
@issy123 yes you are right, 'experienceUpdate' is never getting called.

**Comment by pulviscriptor** [comment]
Probably experience update is now in that `wss://web-live-v3-0.agario.miniclippt.com/ws` server.
@MasonBurdette
Any updates?

**Comment by MasonBurdette** [comment]
@pulviscriptor havent found much time to work on it..  im not really player agar that much anymore :P

**Comment by thisismo** [comment]
OPCode #81 and #102 http://agar.gcommer.com/index.php?title=Protocol

**Comment by pulviscriptor** [comment]
@thisismo
102 is 
```javascript
  case 102:
	r = a.buffer.slice(d);
	m.core.proxy.forwardProtoMessage(r);
	break;
```
and `r` is some binary data that only agar knows and `m` is `windows.agarApp` and `core` is MiniclipAPI and so on...
It sends data to `wss://web-live-v3-0.agario.miniclippt.com/ws` as i understand.

**Comment by issy123** [comment]
@pulviscriptor

Do you have an beautified version of agario's code?

**Comment by pulviscriptor** [comment]
@issy123
I use http://www.jsnice.org/ without renaming. Renaming makes everything worse.

**Comment by SzAmmi** [comment]
@pulviscriptor Does that commented code in account.js work?

**Comment by pulviscriptor** [comment]
@SzAmmi 
There is no packet processors. Somebody need to reverse engineer that protocol.

**Comment by SzAmmi** [comment]
@pulviscriptor Oh, I see.

**Comment by camilleeyries** [comment]
A thing that make we can collect free coin could be nice too....

**Comment by DaAwesomeRazor** [comment]
@pulviscriptor Where could we find where it makes the websocket connection to wss://web-live-v3-0.agario.miniclippt.com/ws. Which file is it in? I tried looking for it.but I could not find it

**Comment by MasonBurdette** [comment]
This really needs implemented, my friend @issy123 already made it (not sure if he wants to share it)

**Comment by philw1508** [comment]
Masen it would be awesome!:)

**Comment by hassanila97** [comment]
@MasonBurdette How old r u, if I can? You sound like a "real programmer" not like the noobs that I often see here on GitHub...  It would be nice though if you shared as it doesn't make anything wrong..  and it can't even be overused as we are limited to 20 coins/hour/account   so...

**Comment by MasonBurdette** [comment]
@hassanila97 it's a possibility, but I don't like releasing things other people can copy. It makes me mad xD

**Comment by MasonBurdette** [comment]
oh im only 12 :P

**Comment by hassanila97** [comment]
@MasonBurdette Oh nice that you're so young and good coder...  I also hate those bitches that steal code and change author...  (fuck those that I just mentioned).... I also did a mega requested code... not Agar.io related nor even international , just local and will not post it free :P as there are bitches...

**Comment by MasonBurdette** [comment]
yea, u skype?

**Comment by hassanila97** [comment]
I have Skype hassanila97@hotmail.com but I won't always be available I'm busy with studies, coding and other stuff...   I reply only when I'm free...

**Comment by DeepSnowNeeL** [comment]
FYI, every packets sent to this websocket is defined in the script http://agar.io/mc/agario.js?v=72 (version number might increase) look for all : agario.proto.X (ctrl+F agario.proto)

**Comment by MasonBurdette** [comment]
@DeepSnowNeeL u the best!

**Comment by camilleeyries** [comment]
@MasonBurdette you are only 12 year old ?? I have 13 xD.

**Comment by DaAwesomeRazor** [comment]
I can do all of those except check level and xp

**Comment by ghost** [comment]
Thanks guys for this issue! It very usefull for my bots 👍

**Comment by ghost** [comment]
I added all these features to my bots
buy mass boost
buy xp boost
change skin
check level
check coins
buy coins with a credit card

**Comment by issy123** [comment]
Nice bro!

**Comment by ghost** [comment]
@issy123 Thx!

**Comment by ghost** [comment]
@issy123 If You want too see my bots go at minions.ovh 👍

**Comment by ghost** [comment]
@issy123 

//CLIENT MASS BOOST 1H
102, //OPCODE

8, 1, //FACEBOOK API VERSION :D

18, 25, //UINT16 CODE!

8, 70, 78, 4, //UINT32 FACEBOOK VERSION :D

20, 10, //SOME UINT16

18, //STRING LENGHT

49, 95, 109, 97, 115, 115, 95, 98, 111, 111, 115, 116, 95, 50, 120, 95, 49, 104 // STRING UFT8

Right? 😀

**Comment by henopied** [comment]
Yea. No. Sorry, that does not count as decoded.
