### ISSUE TITLE
limit on one ip address

### ISSUE THREAD

**Issue by jtiq** [pulviscriptor/agario-client#79]
How to remove the limit on one ip address?

**Comment by MasonBurdette** [comment]
try using proxies
(ex, SOCKS, HTTP)

**Comment by jtiq** [comment]
Limit 3 bots per IP address. In browsers more than 3 connections allowed per IP address. How can we connect more then 3 connections, and authorize them via Facebook provider?

**Comment by MasonBurdette** [comment]
So you got this right:
- 3 Clients per IP
- 1 IP per Facebook

In order to connect more clients, you need to use proxies so each bot connects on a different IP.  For Facebook you would need to have a shit ton of accounts, with a token generator for each one.

**Comment by jtiq** [comment]
Why in browsers I can use more than 3 connections?

**Comment by pulviscriptor** [comment]
@jtiq
From browser you are connecting to random servers.
https://github.com/pulviscriptor/agario-client/issues/53#issuecomment-170940963

**Comment by jtiq** [comment]
thanks
i am try using proxies (socks5)

**Comment by issy123** [comment]
Problem solved? Close the issue :heavy_check_mark:
