### ISSUE TITLE
New changes in agar.io broke client again

### ISSUE THREAD

**Issue by pulviscriptor** [pulviscriptor/agario-client#8]
Now agar.io uses keys for each IP that you need send to server otherwise it will disconnect you.
This will bring lots of pain, I hope it will be removed someday.
I tried to implement it here https://github.com/pulviscriptor/agario-client/tree/server-keys but server don't want to spawn my ball. 
I need go to sleep now and try to fix it later. 
Sorry.

**Comment by pulviscriptor** [comment]
Had to add 2000ms timeout before emitting "connected" event.

**Comment by RouxRC** [comment]
This key thing is a real bummer! :/

Does anyone know whether there's a way to ask m.agar.io a key for a specific server ip?

**Comment by pulviscriptor** [comment]
RouxRC, you can try look here https://www.reddit.com/r/agario
