### ISSUE TITLE
facebook cookies changes each time.

### ISSUE THREAD

**Issue by issy123** [pulviscriptor/agario-client#80]
I have 10 facebook accounts.

It appears that the cookies (datr, c_user and xs) changed in a period of time.
First i could retrieve all 10 tokens but now 2 tokens.

When do the cookies change is there an special case?

How can i prevent this from happening? Or fix this.

**Comment by MasonBurdette** [comment]
one semi-related question:
  how did you get 10 fb accounts
  (whenever i make one i must verify via phone #)

**Comment by issy123** [comment]
Bought them

**Comment by issy123** [comment]
Feedback:

Cookies do indeed change over time, but the older ones still work.
I found out that my facebook accounts were not connected to agario, I did not give the permission yet.

So if u failed to got the token but still got an http 200 status code, maybe it is because u didnt check if the account gave permission to agario
