### ISSUE TITLE
Amount of Balls Connected

### ISSUE THREAD

**Issue by MasonBurdette** [pulviscriptor/agario-client#81]
How would I see how many balls are in the game that are under my client
(ex, see how many bots i have)

**Comment by issy123** [comment]
You mean how many bots you have like raga.pw has?

An bot can have multiple balls so i dont think you mean that.

But you could create an counter.

Add +1 when an bot is spawn subtract -1 if reset or disconnect event is triggered.

 And return the counter with an websocket or what you prefer to show the counter clientside

**Comment by MasonBurdette** [comment]
Thanks @issy123
