### ISSUE TITLE
connection error: error: socket hang up

### ISSUE THREAD

**Issue by agarioBotDev** [pulviscriptor/agario-client#82]
hi pulviscriptor,

getting the error: connection error: error: socket hang up
what happened and any solutions ? :-)

thanks, david

**Comment by pulviscriptor** [comment]
@agarioBotDev
Don't see any problems running `examples/basic.js`.
Can you provide more information?

**Comment by agarioBotDev** [comment]
my programm runs 200 bots, when it works. The problem is it only work 1 of 100 times....normally something about 30 connect and the otherones get a disconnect with the error: socket hang up

**Comment by issy123** [comment]
Maybe the quality of your proxies are bad.

Go check them here: http://www.checker.freeproxy.ru/checker
Be sure it is also from the same type your agent is.

If your script needs socks5 proxy only provide socks5 proxies

**Comment by agarioBotDev** [comment]
i need http proxies... yeah i think it is because of the proxies too, but sometimes it works only if i change the agar.io server...

**Comment by pulviscriptor** [comment]
@agarioBotDev
Can't say what is wrong there and how to fix it.

**Comment by issy123** [comment]
Pulviscriptor is right.
What I was saying is just a guess.

You need to provide more information for an more accurate solution
