### ISSUE TITLE
error: index out of range

### ISSUE THREAD

**Issue by agarioBotDev** [pulviscriptor/agario-client#83]
hello pulviscriptor,

i get the error (in picture) random....it works and then suddenly i get this error..
what it is and what can i do to fix it ?
![1](https://cloud.githubusercontent.com/assets/16101422/12919215/5d87678c-cf43-11e5-9816-ede421449d74.png)

**Comment by Petterholm** [comment]
I get the same error

**Comment by pulviscriptor** [comment]
Check event `packetError` in readme. You need to do `preventCrash()` when event `packetError` happens.

**Comment by Petterholm** [comment]
how can i do that?

**Comment by Petterholm** [comment]
Can you check my issue

**Comment by issy123** [comment]
You need to add this:

`bot.on('packetError', function(packet, err, preventCrash) {
   bot.log('Packet error detected for packet: ' + packet.toString());
   bot.log('Crash will be prevented, bot will be disconnected');
   preventCrash();
   bot.disconnect();
});`

More details here: #46

**Comment by agarioBotDev** [comment]
actually, when i do this, i get annother error
![1](https://cloud.githubusercontent.com/assets/16101422/12932151/a3ef6bfa-cf81-11e5-880f-34dd906ee547.png)

**Comment by pulviscriptor** [comment]
@agarioBotDev 
This is bug in `ws` https://github.com/websockets/ws/issues/669
Check crash 1

**Comment by agarioBotDev** [comment]
@pulviscriptor  thanks !

**Comment by LordMajestros** [comment]
Fixed here https://github.com/websockets/ws/pull/681/commits
