### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Petterholm** [pulviscriptor/agario-client#84]
Hey i get this error https://gyazo.com/7979b459a50db12e0befe84d455395c0
Some error packets: 10 b4 0d 00 00 c3 14 00 00 00 00 00 00, Report this packet: 10 c8 08 00 00 8c 0d 00 00 00 00 00 00

**Comment by pulviscriptor** [comment]
You need to catch `packetError` event and prevent crash https://github.com/pulviscriptor/agario-client/issues/83#issuecomment-181963526

**Comment by Petterholm** [comment]
Where am i supposed to put it

**Comment by pulviscriptor** [comment]
@Petterholm
I don't see your code, i can't say.
If you didn't made your bot yourself, contact person who made it for you, tell him to attach event.

**Comment by Petterholm** [comment]
https://github.com/davidmann4/agario-feeder-bot

**Comment by issy123** [comment]
Write the issue there not here.

Its his code ur executing.
Create an new issue there and refer to this issue.
So he can fix it for you & others using his script
