### ISSUE TITLE
FB

### ISSUE THREAD

**Issue by Butterflypanda** [pulviscriptor/agario-client#86]
well the auth token and the cookies bots just wont connect to server

**Comment by pulviscriptor** [comment]
Make sure you use one FB account per connection. You can't connect twice using one account.

**Comment by Butterflypanda** [comment]
I know but it says bot xxx connected to xxxxxxxxxxx then disconnected to xxxxxxxxxxx

**Comment by Sonicmaster13** [comment]
Agario just updated Main_Out.js but i don't see any errors when i run my 300 facebook level bots (which are super op, you gain like a level per 5 minutes!) so the only thing i can think of is that you are trying to connect to the same server/ were already on the same server as the one you are connecting the bot to...

**Comment by Butterflypanda** [comment]
ah alright thx :)

**Comment by issy123** [comment]
@Butterflypanda

Its weird that you understand sonicmaster but not pulviscriptor while he said the same thing.

Dont forget to close this issue!

**Comment by Sonicmaster13** [comment]
#issy123 lol, yea.
