### ISSUE TITLE
error: not open

### ISSUE THREAD

**Issue by agarioBotDev** [pulviscriptor/agario-client#88]
Hello pulviscriptor,

i'm getting the error:
![agar](https://cloud.githubusercontent.com/assets/16101422/13028326/1a6c826c-d26c-11e5-8641-06862fba800d.png)
can you help me ? =)

greats,
david

**Comment by pulviscriptor** [comment]
Check https://github.com/websockets/ws/issues/669 crash 2
Fix it like i did there for temporary solution. After crash 1 will be fixed https://github.com/websockets/ws/issues/679 i think i will add callback for send and throw `packetError` if socket is no opened on connection.
Until that use temporary solution.

**Comment by agarioBotDev** [comment]
@pulviscriptor did the temporary fix, but don't work:
![agar](https://cloud.githubusercontent.com/assets/16101422/13028906/7ff11466-d27d-11e5-8d17-6108d0ac6cec.png)

**Comment by pulviscriptor** [comment]
Fixed in https://github.com/pulviscriptor/agario-client/commit/1f51f808f06d42ab44bf680aac63ff2c04e7419e
