### ISSUE TITLE
Help on my own agar client?

### ISSUE THREAD

**Issue by Sonicmaster13** [pulviscriptor/agario-client#92]
I have been working on my own version of an agario client in NodeJS, and i have been getting some errors: 

    RangeError: Offset is outside the bounds of the DataView

the lines it is talking about are:
        //of course i required buffer-DataView
	var buf = new ArrayBuffer(message.data); //message.data is the message received from the agario server.
    var dataView = new DataView(buf);

    var i = 0;
    var opcode = dataView.getUint8(i); //this line in specific
    switch (opcode) {
        case 16:
    //blablablabla you get it, just all of the other cases'

**Comment by Sonicmaster13** [comment]
Nope, i'm an idiot. Sorry, i forgot a bit of code before, and i fixed it now

**Comment by issy123** [comment]
If you are making your own agario-client.js public you should create an own repository and manage your issues there

**Comment by Sonicmaster13** [comment]
@issy123 but i'm not, its for my personal uses. I know that pulviscriptor has practice with this, so i wanted to ask him. I solved it myself, though.
