### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by SzAmmi** [pulviscriptor/agario-client#93]
Why does agario-client make multiple connections when I do the connect() only once?

```
worker: connecting...
worker: connecting...
worker: connecting...
worker: connected to server
worker: connected to server
worker: connected to server
worker: disconnect() called
worker: disconnect() called
worker: disconnect() called
worker: disconnected
```

**Comment by issy123** [comment]
Your code does. Give the worker an unique id for example worker1,worker2,worker3 etc

**Comment by pulviscriptor** [comment]
@SzAmmi
Running `examples/basic.js` i can't reproduce your problem.

**Comment by SzAmmi** [comment]
Thanks @issy123 . Problem solved.
