### ISSUE TITLE
Check for Facebook login

### ISSUE THREAD

**Issue by SzAmmi** [pulviscriptor/agario-client#94]
Reference: http://agar.gcommer.com/index.php?title=Protocol#GotLogin_.28opcode_103.29

I added this to Your code in packets (agario-client.js):
```javascript
		'103': function(client, packet) {
			// Got login
			console.log('got login');
			client.emit('gotLogin');
		},
```
and after 5s after connected event to the server I can't see 103 opcode... Of course I did requestFBtoken and I set auth_token before connecting.

**Comment by issy123** [comment]
Did you get an unknown packet warning before adding that code?

**Comment by pulviscriptor** [comment]
@SzAmmi 
I do not see processor for packet ID 103 http://agar.io/main_out.js
That "Reference" may be outdated or wrong. 
Also as @issy123 said, do you see "unknown packet" warnings?

**Comment by SzAmmi** [comment]
@issy123 Nope.
@pulviscriptor No. You're right. Is there any solution to check if I logged in?
@issy123 Nope.
@pulviscriptor No. You're right. Is there any solution to check if I logged in?

**Comment by SzAmmi** [comment]
I don't think so... Probably the solution is: connect to `wss://web-live-v3-0.agario.miniclippt.com/ws` and check for login.

**Comment by SzAmmi** [comment]
NO! BACK! opcode 103 still works to check if i logged in
`worker: [warning] unknown packet ID(103): 67`
If You received opcode 103, You logged in :)

**Comment by pulviscriptor** [comment]
Hmm... Not sure what that packet means because there is no "103" in http://agar.io/main_out.js
I can't name event "gotLogin" without confirmation that it is doing what wiki saying.
I will add empty processor.

**Comment by issy123** [comment]
I got the same warning btw could you emit gotLogon event so i can see my fb account got loggedin

**Comment by pulviscriptor** [comment]
@issy123
You can make event for yourself like this
```javascript
client.on('message', function(packet) {
    if(!packet.length) return; // If bad SOCKS sends empty packet
    var packet_id = packet.readUInt8(0);
    if(packet_id == 103) {
        client.emit('gotLogin');
    }
});
```
When packet 103 will be received, event `gotLogin` will be emitted
```javascript
client.on('gotLogin', function() {
    console.log('Got login!');
});
```

**Comment by SzAmmi** [comment]
@pulviscriptor You can exprience it yourself. Can You make this:
```javascript
        '103': function(client) {
            // Processor for that packet is missing in official client but @SzAmmi reporting that he receives it
            // https://github.com/pulviscriptor/agario-client/issues/94
            client.emit('gotLogin');
        },
```
?

**Comment by pulviscriptor** [comment]
Event added.

**Comment by issy123** [comment]
@pulviscriptor your advice with client.on("message" is not practical, unless you catch those user-defined packet processors packet errors, which is not the case.
In other words packet errors will never be catched with client.on('message')

**Comment by SzAmmi** [comment]
@pulviscriptor Thank You! :)
