### ISSUE TITLE
unknown packet ID(18)

### ISSUE THREAD

**Issue by q3wzeck** [pulviscriptor/agario-client#97]
So we have new packet ID 18. 
http://agar.gcommer.com/index.php?title=Protocol#Reset_all_.28opcode_18.29 says that packet resets the known cells like ID 20.. but in main_out.js there is 2 more parameters for reset. 
`case 18:
                E = [];
                q = [];
                K = {};
                A = [];
                break;
            case 20:
                q = [];
                E = [];
                break;`

**Comment by thisismo** [comment]
why have you closed this issue?

**Comment by pulviscriptor** [comment]
Ball destroy reason `server-forced` added.
