### ISSUE TITLE
New Agar Update

### ISSUE THREAD

**Issue by AmazingGamerBoy** [pulviscriptor/agario-client#98]
Hey, with the new agar update, will the moveTo() function still work?

**Comment by pulviscriptor** [comment]
Don't know what update you mean but `basic.js` works fine.

**Comment by AmazingGamerBoy** [comment]
It's just that agar had an update and peeps are having issues with finding a way to find the location of your ball and then send bots to the location.

**Comment by AmazingGamerBoy** [comment]
Why did you close it? it's a related and totally valid question

**Comment by pulviscriptor** [comment]
But it is not related to `agario-client`. `agario-client` works fine.

**Comment by issy123** [comment]
The `moveTo()` function works.
The coordinations of each client/bot is scrambled with an offset.

For more information i suggest reading older issues or do more google work.

**Comment by AmazingGamerBoy** [comment]
Ok thanks guys
